### PR TITLE
fix: support aggregation with group-by on mixed tag and field columns

### LINKED ISSUE #733: Add MCP Analytics dashboard
### Name and Version

[FE]0.15.0-rc [BE]0.15.0-rc

### What is the problem this feature will solve?

Add MCP Analytics dashboard to Dial Admin Panel

### What is the feature you are proposing to solve the problem?

based on support analytics for MCP requests feature

https://github.com/epam/ai-dial-analytics-realtime/pull/210
https://github.com/epam/ai-dial-analytics-realtime/pull/212

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by oleksii-donets**
### Applicable issues

- fixes #733

### Description of changes

This PR enhances the aggregation engine with two major features and several fixes for InfluxDB 2 (Flux) and InfluxDB 3 (SQL) query builders.

#### 1. CASE WHEN conditional aggregation

Support `SUM(CASE WHEN condition THEN 1 ELSE 0 END)` syntax for conditional counting in a single query.

- **Grammar**: Added `CASE`/`WHEN`/`THEN`/`ELSE`/`END` tokens and `case_when_expression` rule to the ANTLR grammar.
- **CaseWhenExpressionImpl**: New expression node with condition, thenExpression, elseExpression, type inference, and dependent column collection.
- **FluxQueryBuilder**: Translates CASE WHEN into Flux `filter()` + `count()` pipeline.
- **SqlQueryBuilder**: Renders native SQL `SUM(CASE WHEN "col" = $param THEN 1 ELSE 0 END)` with parameterized queries.
- Supports all six comparison operators (=, !=, <, >, <=, >=).

#### 2. Combined window + column aggregation (GROUP BY)

Allow `GROUP BY window(_time, 1, 'd'), column` — grouping by both a time window and columns simultaneously.

- **AbstractQueryBuilder**: New `isWindowColumnAggregationQuery()` detection and `buildWindowColumnAggregationQuery()` abstract method.
- **FluxQueryBuilder**: Builds separate per-function aggregation queries, then joins on window boundaries + column names.
- **SqlQueryBuilder**: Uses `DATE_BIN(interval, time_column, epoch)` for windowing with GROUP BY on window alias + all column names.

#### 3. Fixes for mixed tag+field group-by and missing columns

- **SqlQueryBuilder**: Only include group-by columns in SQL SELECT when they appear in expressions, preventing column position mismatch.
- **FluxQueryBuilder**: Switch aggregation queries to `fieldsAsCols()` pivot instead of field filtering, enabling group-by on field columns. Exclude group-by columns from `count()` target to avoid Flux's "cannot aggregate columns that are part of the group key" error.
- **FluxQueryBuilder**: Use `_measurement` for `count()` instead of an arbitrary schema column that may be absent from actual data, preventing "column does not exist" errors.

#### 4. Test coverage

- **AbstractInfluxContainerTest**: Shared integration tests (totalCount, sumTokens, countDistinctUsers, missing column scenarios, window aggregations, conditional CASE WHEN counting, single/multi-column group-by, mixed tag+field group-by, window+column aggregation) running against both InfluxDB 2 and InfluxDB 3 engines.
- **New `mcp_analytics` table** in test configs and seed data (without `project_id` tag) to verify `count()` works when schema-defined columns are absent from actual data.
- **FluxQueryBuilderTest / SqlQueryBuilderTest**: Unit tests for new query generation paths.
- Improved assertion style: `containsExactly()` with column names and recursive comparison for floating-point values.

### Checklist

- [X] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by KirylKurnosenka — DISMISSED** [review]

**Review by siarhei-fedziukovich — DISMISSED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java [hunk 1]
```diff
@@ -321,6 +324,136 @@ protected FluxQueryContext buildWindowAggregationQuery(Query query) {
...
+                        groupByColumnNames,
+                        groupFunctionCall,
+                        aggCall,
+                        regexCounter))
+                .toList();
+
+        if (aggregations.size() == 1) {
+            combiner.add(aggregations.get(0));
+        } else {
+            var joinColumns = new ArrayList<String>();
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java:356]: Should all this stuff be done if aggregations is emtpy?

File: src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java [hunk 2]
```diff
@@ -321,6 +324,136 @@ protected FluxQueryContext buildWindowAggregationQuery(Query query) {
...
+            Filter filter,
+            List<String> groupByColumnNames,
+            com.epam.aidial.expressions.GroupFunctionCall groupFunctionCall,
+            AggregationFunctionCall aggregationFunctionCall,
+            AtomicInteger regexCounter
+    ) {
+        var function = (FunctionImpl) aggregationFunctionCall.getFunction();
+        var args = aggregationFunctionCall.getArgs();
+
+        InfluxTableDeclaration tableDeclaration = getTableDeclaration(tableName);
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java]: all variables are declared using `var` except this one. Is it for purpose?

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java (hunk 1 above)
Comment (oleksii-donets) [reply src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java:356]: Added an if branch for the case when aggregations is empty

File: src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java (hunk 2 above)
Comment (oleksii-donets) [reply src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java]: changed to var

**Review by KirylKurnosenka — APPROVED** [review]
