### PR TITLE
fix: `applicationTypeBucketCopy` to upper case + minor code cleanup

### LINKED ISSUE #334: [Models] Model created in Admin panel UI does not appear in Chat
### Name and Version

0.10.0

### What steps will reproduce the bug?

Steps to Reproduce:
Open Admin panel.
Create a new model.
Save.
Open Chat and check the model list.

### What is the expected behavior?

The model should appear in the Chat after being created in Admin panel.

### What do you see instead?

The model created in Admin does not appear in the Chat.
In the logs, the following warning appears:
WARN Failed to reload config: All custom application type schemas should conform to meta schema

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #334

### Description of changes
Changed `applicationTypeBucketCopy` to upper case

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/main/java/com/epam/aidial/cfg/domain/mapper/ApplicationTypeSchemaCoreMapper.java [hunk 1]
```diff
@@ -23,28 +20,22 @@ public abstract class ApplicationTypeSchemaCoreMapper {
...
     private final ObjectMapper objectMapper = JsonMapperConfiguration.createJsonMapper();
 
-    @Autowired
-    private ApplicationTypeSchemaRouteCoreMapper applicationTypeSchemaRouteCoreMapper;
-
     public String mapToCoreString(ApplicationTypeSchema applicationTypeSchema) {
         if (applicationTypeSchema == null) {
             return null;
         }
-        var routes = applicationTypeSchemaRouteCoreMapper.map(applicationTypeSchema.getApplicationTypeRoutes());
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/domain/mapper/ApplicationTypeSchemaCoreMapper.java:33]: removed manual mapping since mapstruct is able to do that on its own

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by Katerina-Charakhovich — APPROVED** [review]
