### PR TITLE
fix: Missing validation for importing duplicated prompts.

### LINKED ISSUE #858: [Assets-Prompts] Missing validation for importing duplicated prompts.
### EPAM AI DIAL Admin version

Admin: [FE]0.16.0-rc [BE]0.16.0-rc

### How to reproduce

Reference to https://github.com/epam/ai-dial-admin-frontend/issues/2926

DEV environment

**Preconditions:**
1. ZIP file or JSON with some prompts in one file is exported.
2. Change file the way that it has some duplicated prompts inside and save this changes.

**Steps:**
1. Navigate to Assets->Prompts
2. Select any folder.
3. Click 'Create' button.
4. Click 'Import' button.
5. Select JSON or ZIP as a file type.
6. Switch the toggle 'Ignore paths' to ON -> Next
7. Select as conflict resolution Overridden or Skipped.
9. Click 'Finish'.
**NOTE: Select Edit manually and observe that there are no any conflicts.**

### Actual result

Import failed with Bad Request and not clear explanation why it happens.

Image

### Expected result

Importing files are validated before import starts. 
The user sees a clear error message.
As an example we can take error messages from Figma.

Image

Image

### Additional information

_No response_

### Confidential information

- [x] I confirm that do not share any confidential information

### PR DESCRIPTION
**Pull request by Katerina-Charakhovich**
### Applicable issues

- fixes #858 

### Checklist

- [ ] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/service/prompt/PromptEximService.java [hunk 1]
```diff
@@ -181,7 +196,11 @@ private ImportResourcesResult createPromptOrThrow(CreatePrompt createPrompt,
                                                       String targetPath,
                                                       ImportConflictResolutionStrategy conflictResolutionStrategy) {
         try {
-            promptService.createPrompt(createPrompt);
+            if (conflictResolutionStrategy == ImportConflictResolutionStrategy.SKIP) {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/service/prompt/PromptEximService.java:199]: What would be the result in case conflict strategy is SKIP and prompt already exists?

File: src/main/java/com/epam/aidial/cfg/service/prompt/PromptImportValidator.java [hunk 2]
```diff
@@ -20,42 +21,47 @@
...
-        }
-        if (!duplicatedPromptNames.isEmpty()) {
-            duplicatedPromptNames.forEach((promptName, promptIds) ->
-                    errorMessage.append("\n  - Duplicated prompt name %s for IDs: %s".formatted(promptName, promptIds))
-            );
-        }
-        throw new IllegalArgumentException(errorMessage.toString());
+        var errorsByPromptId = new LinkedHashMap<String, String>();
+        duplicatedPromptIds.forEach((id, count) ->
+                addError(errorsByPromptId, id, "Duplicate prompt id: \"%s\" appears %d in the import file."
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/service/prompt/PromptImportValidator.java]: 1) Duplicate**d**
2) "... appears 3 in the import file.". I think "time(s)" word is missing, so it would look like "... appears 3 time(s) in the import file.

File: src/main/java/com/epam/aidial/cfg/service/prompt/PromptEximService.java (hunk 1 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/service/prompt/PromptEximService.java:199]: In case the conflict strategy is SKIP and the prompt already exists, the result for that prompt will be returned as a failure entry in importResults, for example:

{
  "sourcePath": "public/test_prompts/Date__1.0.0",
  "targetPath": "public/Date__1.0.0",
  "status": "failure",
  "error": "Prompt with name Date already exists"
}

Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/service/prompt/PromptEximService.java:199]: I'm not sure how that worked before, but shouldn't we silently skip such prompt instead of trying to create it and getting failure as it's done for our config entities?

File: src/main/java/com/epam/aidial/cfg/service/prompt/PromptImportValidator.java (hunk 2 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/service/prompt/PromptImportValidator.java]: Updated

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/service/prompt/PromptEximService.java (hunk 1 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/service/prompt/PromptEximService.java:199]: updated, now it will return 
{
"sourcePath": "public/test_prompts/Date__1.0.0",
"targetPath": "public/Date__1.0.0",
"status": "already_exists"
}

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/test/java/com/epam/aidial/cfg/service/prompt/PromptEximServiceTest.java [hunk 3]
```diff
@@ -58,6 +62,11 @@ class PromptEximServiceTest {
     @Autowired
     private PromptEximService promptEximService;
 
+    @BeforeEach
+    void stubUniquenessValidator() {
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/service/prompt/PromptEximServiceTest.java]: I'd suggest to use more generic name, so there is no need to rename method if in future more stubbings for other mock beans will be specified here
I'm not even sure whether stubbing should be run before each test considering that there are export tests which do not require validator at all

Comment (Katerina-Charakhovich) [reply src/test/java/com/epam/aidial/cfg/service/prompt/PromptEximServiceTest.java]: done

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by KirylKurnosenka — APPROVED** [review]
