### PR TITLE
fix: exclude "roleLimits" field from deployments for config export in Admin format

### LINKED ISSUE #109: [Export Config] Exported Admin config contains roleLimits for models, applications, routes
### Name and Version

dial-admin-backend 0.5.0

### What steps will reproduce the bug?

1. Export full config in Admin format
2. Look at `deployment` field in models, applications, routes

### What is the expected behavior?

`deployment` field in models, applications, routes should not have `roleLimits` field

### What do you see instead?

`deployment` field in models, applications, routes has `roleLimits` field, e.g. `qayk` model

Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #109 

### Description of changes

Exclude `roleLimits` field from deployments for config export in Admin format

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/service/transfer/exporter/RouteExporter.java [hunk 1]
```diff
@@ -88,8 +90,8 @@ protected Collection<ExportComponentInfo> preview(ExportRequest request) {
                 .collect(Collectors.toList());
     }
 
-    private Route removeDependency(Route route, Set<ExportConfigComponentType> componentTypes) {
-        if (!componentTypes.contains(ExportConfigComponentType.ROLE)) {
+    private Route removeDependency(Route route, Set<ExportConfigComponentType> componentTypes, ExportFormat exportFormat) {
+        if (!componentTypes.contains(ExportConfigComponentType.ROLE) || exportFormat == ExportFormat.ADMIN) {
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/service/transfer/exporter/RouteExporter.java:96]: leave comment pls.

Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/service/transfer/exporter/RouteExporter.java:96]: Left comment

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by siarhei-fedziukovich — APPROVED** [review]
