### PR TITLE
fix: [Folders] Move to operations fail on name conflict

### LINKED ISSUE #854: [Assets][Files/Prompts/Folders] Bad Request: Move to operations fail on name conflict
### EPAM AI DIAL Admin version

[FE]0.16.0-rc [BE]0.16.0-rc

### How to reproduce

**Preconditions:**
• File or prompt exists in **Folder A**
• File or prompt with the same name (and same version for prompts) already exists in **Folder B**

**Affected:**
• Asset -> Files
• Asset -> Prompts
_• Asset -> Toolsets
• Asset -> Applications_
 **Affected also Folder with Files/ Prompts _/Toolsets/Applications_**

**Steps to Reproduce:**
1. Go to Assets (Files or Prompts)
2. Select an File from **Folder A**
3. Click **Move to** and choose **Folder B** (where an item with the same name (_and version for Prompt)_ already exists)
4. In the popup “**Replace or Duplicate item**”, select either Replace or Duplicate

### Actual result

Item is not moved (replaced, or duplicated). Message “**Bad request. Can't move resource files _[path]_ to _[path]_, because destination resource already exists”**

Image

### Expected result

Selected action (Replace or Duplicate) are successfully processed.

### Additional information

_No response_

### Confidential information

- [x] I confirm that do not share any confidential information

### PR DESCRIPTION
**Pull request by Katerina-Charakhovich**
### Applicable issues

- fixes #854 

### Checklist

- [ ] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/test/java/com/epam/aidial/cfg/service/FolderServiceTest.java [hunk 1]
```diff
@@ -42,12 +44,15 @@ void init() {
         conversationService = mock(ConversationService.class);
         fileService = mock(FileService.class);
         promptService = mock(PromptService.class);
+        toolSetService = mock(ResourceService.class);
+        when(toolSetService.getResourceType()).thenReturn(ResourceType.TOOL_SET);
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/service/FolderServiceTest.java]: Is this needed?

File: src/test/java/com/epam/aidial/cfg/service/FolderServiceTest.java [hunk 2]
```diff
@@ -241,36 +242,36 @@ void testMoveFolder_oldFolderDoesNotExist_exceptionIsThrown() {
...
+        doNothing().when(publicationService).approvePublication("pub");
 
-        when(applicationService.getFolders(newResourceMetadataRequest)).thenReturn(FolderInfo.builder().build());
-        when(conversationService.getFolders(newResourceMetadataRequest)).thenReturn(null);
-        when(fileService.getFolders(newResourceMetadataRequest)).thenReturn(null);
-        when(promptService.getFolders(newResourceMetadataRequest)).thenReturn(null);
+        String fileUrl = "files/public/old/item.json";
+        String destUrl = "files/public/new/item.json";
+        when(fileService.getResourceUrls(oldPath)).thenReturn(Set.of(fileUrl));
+        doNothing().when(fileService).move(argThat(m ->
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/service/FolderServiceTest.java]: Can't we create MoveResource object with `fileUrl`, `destUrl` and `true` values and use it here and in verification as well?

File: src/main/java/com/epam/aidial/cfg/service/FolderService.java [hunk 3]
```diff
@@ -221,7 +205,9 @@ private void copyFolderRules(String oldPath, String newPath) {
         updatesRules(updateRulesRequest);
     }
 
-    private void moveResources(String oldPath, String newPath, List<ResourceType> resourceTypes) {
+    private void moveResources(MoveFolderRequest moveFolderRequest, List<ResourceType> resourceTypes) {
+        String oldPath = moveFolderRequest.getOldPath();
+        String newPath = moveFolderRequest.getNewPath();
         log.debug("moveResources. oldPath: {}, newPath: {}, resourceTypes: {}", oldPath, newPath, resourceTypes);
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/service/FolderService.java]: please either add logging of `overwrite` flag, or just log entire `moveFolderRequest` object

Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/service/FolderService.java]: updated

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/service/FolderService.java [hunk 4]
```diff
@@ -221,8 +205,10 @@ private void copyFolderRules(String oldPath, String newPath) {
         updatesRules(updateRulesRequest);
     }
 
-    private void moveResources(String oldPath, String newPath, List<ResourceType> resourceTypes) {
-        log.debug("moveResources. oldPath: {}, newPath: {}, resourceTypes: {}", oldPath, newPath, resourceTypes);
+    private void moveResources(MoveFolderRequest moveFolderRequest, List<ResourceType> resourceTypes) {
+        String oldPath = moveFolderRequest.getOldPath();
+        String newPath = moveFolderRequest.getNewPath();
+        log.debug("moveResources. request: {}", moveFolderRequest);
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/service/FolderService.java]: resourceTypes were removed from log

File: src/test/java/com/epam/aidial/cfg/service/FolderServiceTest.java [hunk 5]
```diff
@@ -241,36 +242,35 @@ void testMoveFolder_oldFolderDoesNotExist_exceptionIsThrown() {
...
-        // then
-        Assertions.assertThatThrownBy(() -> folderService.moveFolder(moveFolderRequest))
-                .isInstanceOf(FolderAlreadyExistsException.class)
-                .hasMessage("Folder: public/new1/new2 already exists in APPLICATION resources");
+        MoveResource moveResource = new MoveResource(fileUrl, destUrl, true);
+        doNothing().when(fileService).move(eq(moveResource));
+
+        folderService.moveFolder(moveFolderRequest);
+
+        verify(fileService).move(argThat(MoveResource::isOverwrite));
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/service/FolderServiceTest.java]: `.move(moveFolderRequest)` instead of `.move(argThat(...))`

File: src/test/java/com/epam/aidial/cfg/service/FolderServiceTest.java [hunk 6]
```diff
@@ -241,36 +242,35 @@ void testMoveFolder_oldFolderDoesNotExist_exceptionIsThrown() {
...
+        String fileUrl = "files/public/old/item.json";
+        String destUrl = "files/public/new/item.json";
+        when(fileService.getResourceUrls(oldPath)).thenReturn(Set.of(fileUrl));
 
-        // then
-        Assertions.assertThatThrownBy(() -> folderService.moveFolder(moveFolderRequest))
-                .isInstanceOf(FolderAlreadyExistsException.class)
-                .hasMessage("Folder: public/new1/new2 already exists in APPLICATION resources");
+        MoveResource moveResource = new MoveResource(fileUrl, destUrl, true);
+        doNothing().when(fileService).move(eq(moveResource));
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/service/FolderServiceTest.java]: `eq` is redundant

File: src/main/java/com/epam/aidial/cfg/service/FolderService.java (hunk 4 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/service/FolderService.java]: updated

**Comment by ai-dial-actions** [comment]
⚠️ Dependency review workflow failed - results may be outdated. [Check logs](https://github.com/epam/ai-dial-admin-backend/actions/runs/24776793506)

**Review by KirylKurnosenka — APPROVED** [review]

**Comment by ai-dial-actions** [comment]
⚠️ Dependency review workflow failed - results may be outdated. [Check logs](https://github.com/epam/ai-dial-admin-backend/actions/runs/24779181641)
