### PR TITLE
fix: fix core roles merger when config parts are null

### LINKED ISSUE #162: Add ability to initialize admin app from config files used by core
### Name and Version

0.5.2

### What is the problem this feature will solve?

Currently, the admin app's initial configuration can only be set up by calling the import endpoint, which requires tokens if security is enabled. This process can be cumbersome and limits flexibility, especially in environments where automated or streamlined configuration management is preferred. There is a need to support initialization from various configuration sources such as files, Kubernetes secrets, Kubernetes ConfigMaps, and Vaults to enhance the ease of deployment and management of the admin app.

### What is the feature you are proposing to solve the problem?

We propose adding the ability to initialize the admin app from configuration files used by the core service. This feature should support all types of configuration sources, including files, Kubernetes secrets, Kubernetes ConfigMaps, and Vaults. The initialization from these configuration sources should be controlled by an environment variable, which will be set to false by default to maintain current behavior. When enabled, the admin app should be able to read and apply configurations from the specified sources, streamlining the setup process and improving integration with various deployment environments.

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #162 

### Description of changes
Added `null` handling for missing config parts when merging core roles

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/service/transfer/importer/util/CoreRolesMerger.java [hunk 1]
```diff
@@ -29,7 +33,7 @@ public class CoreRolesMerger {
     private final RoleCoreMapper roleCoreMapper;
 
     public Map<String, Role> mergeCoreRoles(Config config, boolean createRoleIfAbsent) {
-        Map<String, CoreRole> roles = config.getRoles();
+        Map<String, CoreRole> roles = MapUtils.emptyIfNull(config.getRoles());
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/service/transfer/importer/util/CoreRolesMerger.java:36]: Null handling is added due to https://github.com/epam/ai-dial-admin-backend/blob/8c660e71981023fca2a137f852102976213b98cf/src/main/java/com/epam/aidial/cfg/service/impl/storage/ConfigUtils.java#L35

**Review by siarhei-fedziukovich — APPROVED** [review]
