### PR TITLE
fix: remove application type schema that doesn't conform to meta schema and associated applications from exported core config

### LINKED ISSUE #214: [Application Runners] Invalid runners with empty upstream endpoint in App Routes break manual and automatic core config export
### Name and Version

0.7.0-rc

### What steps will reproduce the bug?

Description:
When an application runner is created and inside it an app route is added with empty upstream endpoint, it means application runner does not conform to the meta schema and it causes issues with exporting the configuration.

Steps to Reproduce:

Create an application runner.
Inside this runner, create an app route as in picture below.
Leave the upstream endpoint field empty.
Click Save 
Wait for automatic core config export → fails.
Image

Try to export the core config manually → receive error:

Image

### What is the expected behavior?

System should validate application runners and app routes before exporting.
Invalid runners (not matching meta schema, missing upstream endpoints) should be skipped or rejected gracefully.
All applications inside such invalid runners should also be excluded from export.
Core config export should continue working without being blocked by invalid runners.

### What do you see instead?

Saving fails with error.
Manual export fails with "Config export failed".
Automatic export also fails.
Applications tied to the invalid runner are still included in export, which should not happen.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #214 

### Description of changes
Remove application type schema that doesn't conform to meta schema and associated applications from exported core config

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by Pasichniuk — DISMISSED** [review]

File: src/main/java/com/epam/aidial/cfg/service/normalizer/impl/ApplicationTypeSchemaCoreConfigNormalizer.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+    public void normalize(Config config) {
+        Map<String, String> applicationTypeSchemas = config.getApplicationTypeSchemas();
+        if (MapUtils.isEmpty(applicationTypeSchemas)) {
+            return;
+        }
+
+        for (Map.Entry<String, String> entry : applicationTypeSchemas.entrySet()) {
+            String schemaId = entry.getKey();
+            if (!SchemaConformToMetaSchemaValidator.isValid(entry.getValue())) {
+                log.debug("normalizeConfig. remove invalid application type schema which doesn't conform to meta schema: {}", schemaId);
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/service/normalizer/impl/ApplicationTypeSchemaCoreConfigNormalizer.java]: log.warn until we pull info about appSchema invalidity to dto/FE

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/service/normalizer/impl/ApplicationTypeSchemaCoreConfigNormalizer.java (hunk 1 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/service/normalizer/impl/ApplicationTypeSchemaCoreConfigNormalizer.java]: changed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/service/normalizer/impl/ApplicationTypeSchemaCoreConfigNormalizer.java [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+        Map<String, CoreApplication> applications = config.getApplications();
+
+        for (Map.Entry<String, String> entry : new HashMap<>(applicationTypeSchemas).entrySet()) {
+            String schemaId = entry.getKey();
+            if (!SchemaConformToMetaSchemaValidator.isValid(entry.getValue())) {
+                log.warn("normalizeConfig. remove invalid application type schema which doesn't conform to meta schema: {}", schemaId);
+                applicationTypeSchemas.remove(schemaId);
+
+                List<String> applicationsWithInvalidAppTypeSchema = applications.entrySet().stream()
+                        .filter(appEntry -> appEntry.getValue().getApplicationTypeSchemaId().toString().equals(schemaId))
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/service/normalizer/impl/ApplicationTypeSchemaCoreConfigNormalizer.java:36]: NPE if applicationTypeSchema is not defined for app

Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/service/normalizer/impl/ApplicationTypeSchemaCoreConfigNormalizer.java:36]: also pls add to tests this case

Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/service/normalizer/impl/ApplicationTypeSchemaCoreConfigNormalizer.java:36]: Nice catch, thanks, fixed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by siarhei-fedziukovich — APPROVED** [review]
