### PR TITLE
fix: set completion endpoint path in model's adapter source

### LINKED ISSUE #702: completionEndpointPath missing when assign Model to Adapter
### EPAM AI DIAL Admin version

0.14.0

### How to reproduce

1. Create adapter vid Deployments or via entities
2. Open Adapter go to Models tab.
3. Assign model.
4. Check the model

### Actual result

`The field is required` is displayed in Adapter field of the model after adding model to adapter

Image

Image

### Expected result

`The field is required` isn't displayed in Adapter field of the model after adding model to adapter, completionEndpointPath is present in source

### Additional information

_No response_

### Confidential information

- [x] I confirm that do not share any confidential information

### PR DESCRIPTION
**Pull request by Pasichniuk**
### Applicable issues

- fixes #702 

### Description of changes

On adapter update, if adapter.models have new entries, each model is indirectly updated to use that adapter. This process should also include value population for 'adapterCompletionEndpointPath' since it is required when model source is adapter.

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/dao/mapper/AdapterEntityMapper.java [hunk 1]
```diff
@@ -55,11 +62,15 @@ public AdapterEntity toEntity(Adapter domain,
...
-                        app.setModelContainer(null);
-                        app.setAdapter(updatedEntity);
-                        app.setEndpoint(null);
+                        model.setModelContainer(null);
+                        model.setAdapter(updatedEntity);
+                        model.setEndpoint(null);
+
+                        boolean isChat = isChat(model.getType());
+                        String endpointEnding = ENDPOINT_ENDING_MAP.get(isChat);
+                        model.setAdapterCompletionEndpointPath("%s/%s".formatted(model.getId(), endpointEnding));
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/dao/mapper/AdapterEntityMapper.java]: can we hide this logic behind ModelEndpointUtils? smth like
```
model.setAdapterCompletionEndpointPath(ModelEndpointUtils.getAdapterCompletionEndpointPath(...));
```

Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/dao/mapper/AdapterEntityMapper.java]: Refactored

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/domain/utils/ModelEndpointUtils.java [hunk 2]
```diff
@@ -46,6 +52,16 @@ public ModelEndpointComponents parseModelEndpoint(String modelEndpoint, ModelTyp
         return new ModelEndpointComponents(getValueFromMatcherGroup(matcher, 1), getValueFromMatcherGroup(matcher, 2) + endpointEnding);
     }
 
+    public static String getAdapterCompletionEndpointPath(ModelTypeEntity type, String id) {
+        boolean isChat = isChat(type);
+        String endpointEnding = ENDPOINT_ENDING_MAP.get(isChat);
+        return "%s/%s".formatted(id, endpointEnding);
+    }
+
+    private static boolean isChat(ModelTypeEntity type) {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/domain/utils/ModelEndpointUtils.java:56]: There is such method already, it could it made static

File: src/main/java/com/epam/aidial/cfg/domain/utils/ModelEndpointUtils.java [hunk 3]
```diff
@@ -46,6 +52,16 @@ public ModelEndpointComponents parseModelEndpoint(String modelEndpoint, ModelTyp
         return new ModelEndpointComponents(getValueFromMatcherGroup(matcher, 1), getValueFromMatcherGroup(matcher, 2) + endpointEnding);
     }
 
+    public static String getAdapterCompletionEndpointPath(ModelTypeEntity type, String id) {
+        boolean isChat = isChat(type);
+        String endpointEnding = ENDPOINT_ENDING_MAP.get(isChat);
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/domain/utils/ModelEndpointUtils.java]: MODEL_PATTERN_MAP.get(isChat).getLeft(); in order to not introduce new Map

File: src/main/java/com/epam/aidial/cfg/domain/utils/ModelEndpointUtils.java (hunk 2 above)
Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/domain/utils/ModelEndpointUtils.java:56]: There is no method for ModelTypeEntity

File: src/main/java/com/epam/aidial/cfg/domain/utils/ModelEndpointUtils.java (hunk 3 above)
Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/domain/utils/ModelEndpointUtils.java]: Done

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by KirylKurnosenka — APPROVED** [review]
