### PR TITLE
fix: Passing-empty-objects-instead-of-null

### LINKED ISSUE #716: [Application Runner] Passing empty objects instead of null
### Name and Version

Admin:  [BE]0.14.0-rc

### What steps will reproduce the bug?

1. Configure Application Runner with applicationTypeSchemaEndpoint.
2. Do not provide values for inline schema fields ($defs, properties, etc.).
3. During mapping, empty maps ({}) are created instead of keeping these fields null.
4. Core receives and persists these empty objects.

### What is the expected behavior?

If inline schema fields are not provided, they should remain null and must not be converted into empty maps.

### What do you see instead?

When values are absent, empty maps ({}) are created for $defs, properties

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Katerina-Charakhovich**
### Applicable issues

- fixes #716

### Checklist

- [ ] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/dao/mapper/PropertiesEntityMapper.java [hunk 1]
```diff
@@ -16,18 +18,18 @@ public abstract class PropertiesEntityMapper {
...
+            return null;
         }
         return objectMapper.readValue(value, new TypeReference<>() {
         });
     }
 
     @SneakyThrows
     public String mapFromStringMap(Map<String, String> value) {
-        if (value == null) {
+        if (MapUtils.isEmpty(value)) {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/dao/mapper/PropertiesEntityMapper.java]: What's the reason of mapping empty map to null?

File: src/main/java/com/epam/aidial/cfg/dao/mapper/PropertiesEntityMapper.java [hunk 2]
```diff
@@ -16,18 +18,18 @@ public abstract class PropertiesEntityMapper {
 
     @SneakyThrows
     public Map<String, String> mapToStringMap(String value) {
-        if (value == null) {
-            return Map.of();
+        if (StringUtils.isBlank(value)) {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/dao/mapper/PropertiesEntityMapper.java]: I'm not sure how blank string could be passed here (except case when someone directly changed column value to empty string), but I'd prefer to see an error that empty string can not be mapped to Map instead of silently map it to null

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by KirylKurnosenka — APPROVED** [review]

File: src/main/java/com/epam/aidial/cfg/dao/mapper/PropertiesEntityMapper.java (hunk 2 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/dao/mapper/PropertiesEntityMapper.java]: done

File: src/main/java/com/epam/aidial/cfg/dao/mapper/PropertiesEntityMapper.java (hunk 1 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/dao/mapper/PropertiesEntityMapper.java]: done

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>
