### PR TITLE
fix: remove applications that doesn't conform to their schemas from exported core config, remove keys without roles from manually exported core config

### LINKED ISSUE #117: [Export Config] Export in Core config fails
### Name and Version

dial-admin-backend 0.6.0

### What steps will reproduce the bug?

1. Open Application Runner with "App runner with required fields" display name
2. Open Applications tab
3. Add "kk-test" application and click save
4. Export full config in Core format

### What is the expected behavior?

Config exported successfully

### What do you see instead?

Error occurred while exporting, please try again.
Image

### Additional information

_No response_

### LINKED ISSUE #118: [Export Config] Keys without roles are present in manually exported Core config
### Name and Version

dial-admin-backend 0.6.0

### What steps will reproduce the bug?

1. Go to Keys and remember keys with status "No roles assigned"
2. Export full config in Core format with included secrets

### What is the expected behavior?

Keys without roles are not exported.

### What do you see instead?

Key without roles are present in file, e.g. AI_DIAL_KEY
Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #117
- fixes #118

### Description of changes

- Applications that doesn't conform to their schemas are removed from exported Core config
- Keys without roles are removed from manually (on UI) exported Core config

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/core/config/validation/CustomApplicationConformToTypeSchemaValidator.java [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+    public static Set<ValidationMessage> validate(CoreApplication application,
+                                                  CustomApplicationConformToTypeSchemaValidationContext validationContext) {
+        URI schemaId = application.getApplicationTypeSchemaId();
+        if (schemaId == null) {
+            return Set.of();
+        }
+
+        if (application.getApplicationProperties() == null) {
+            return Set.of();
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/core/config/validation/CustomApplicationConformToTypeSchemaValidator.java:31]: why? if schema has required properties app looks incorrect, isn't it?

Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/core/config/validation/CustomApplicationConformToTypeSchemaValidator.java:31]: but if it the same as in core we can left as is

**Review by siarhei-fedziukovich — APPROVED** [review]

File: src/main/java/com/epam/aidial/core/config/validation/CustomApplicationConformToTypeSchemaValidator.java (hunk 1 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/core/config/validation/CustomApplicationConformToTypeSchemaValidator.java:31]: I'm not sure why as well, as you mentioned, the code is just extracted from constraint validator into separate validator which is spring bean
