### PR TITLE
fix: make key `project` field required

### LINKED ISSUE #315: [Keys] Project field is not validated as required during key creation
### Name and Version

0.10.0

### What steps will reproduce the bug?

Go to Access Management → Keys.
Click Create Key.
Leave the Project field empty.
Click Create — the key is successfully created.
(Note) If you initially fill the Project field and then clear it, the field becomes required as expected.

### What is the expected behavior?

The Project field should always be mandatory during key creation, regardless of whether it was previously filled or not.

### What do you see instead?

The Project field is not required — a key can be created without assigning a project.

Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #315

### Description of changes
Made key `project` field required

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/domain/validator/KeyValidator.java [hunk 1]
```diff
@@ -60,11 +61,18 @@ public void validateUpdate(String keyName, Key key, KeyEntity existingEntity) {
...
         Long expiresAt = key.getExpiresAt();
         long createdAt = existingEntity.getCreatedAt();
         if (expiresAt != null && expiresAt <= createdAt) {
             throw new IllegalArgumentException("Key expiresAt ms: '" + expiresAt + "' should be greater than key createdAt ms: '" + createdAt + "'");
         }
     }
+
+    private void validateProject(String project) {
+        if (StringUtils.isBlank(project)) {
+            throw new IllegalArgumentException("Invalid project: '" + project + "'");
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/domain/validator/KeyValidator.java]: make message more informative

**Review by siarhei-fedziukovich — DISMISSED** [review]

File: src/main/java/com/epam/aidial/cfg/domain/validator/KeyValidator.java (hunk 1 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/domain/validator/KeyValidator.java]: updated

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by siarhei-fedziukovich — APPROVED** [review]

**Review by siarhei-fedziukovich — APPROVED** [review]
