### PR TITLE
fix: #601 [Audit / Identity] missing email for Entra users in audit logs 

### LINKED ISSUE #601: [Audit / Identity] missing email for Entra users in audit logs
### Name and Version

0.13.0

### What steps will reproduce the bug?

Log in to the system using Entra (not through Keycloak).
Perform any action that is recorded in Audit logs (create/update/delete an entity).
Open Audit / Activities and check the user information.

### What is the expected behavior?

Audit logs should correctly display email for users from all providers, including Entra.

### What do you see instead?

Audit records for Entra users do not contain email.

User identity information is incomplete.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Katerina-Charakhovich**
### Applicable issues

- fixes #601

### Checklist

- [ ] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+    }
+
+    public void setJwtGrantedAuthoritiesConverter(
+            Converter<Jwt, Collection<GrantedAuthority>> jwtGrantedAuthoritiesConverter) {
+        Assert.notNull(jwtGrantedAuthoritiesConverter, "jwtGrantedAuthoritiesConverter cannot be null");
+        this.jwtGrantedAuthoritiesConverter = jwtGrantedAuthoritiesConverter;
+    }
+
+    public void setPrincipalClaimName(String principalClaimName) {
+        Assert.hasText(principalClaimName, "principalClaimName cannot be empty");
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java]: why do you use Assert here? usually we validate params w/o Assert in this project

File: docs/configuration.md [hunk 2]
```diff
@@ -129,6 +129,7 @@ Applied when: config.rest.security.mode=oidc
 | providers.*.audiences     | providers.azure.audiences         | Yes      | config.rest.security.mode=oidc | List of accepted JWT token audiences. Specifies the intended recipients of the authorization token as defined in its aud claim. |
 | providers.*.role-claims   | providers.azure.role-claims       | No       | config.rest.security.mode=oidc | Comma-separated list of JWT claim paths used to extract user roles for the provider.                                            |
 | providers.*.allowed-roles | providers.azure.allowed-roles     | No       | config.rest.security.mode=oidc | Comma-separated list of roles with access permissions for the provider                                                          |
+| providers.*.role-claims   | providers.azure.role-claims       | No       | config.rest.security.mode=oidc | Comma-separated list of JWT claim paths used to extract user email                                                              |
```
Comment (siarhei-fedziukovich) [inline docs/configuration.md]: add `CLAIMS_EMAIL_KEY` in configuration.md too

File: src/main/java/com/epam/aidial/cfg/web/security/SecurityConfiguration.java [hunk 3]
```diff
@@ -42,25 +37,9 @@ public class SecurityConfiguration {
...
-                tmpRolesByIssuer.put(issuer, acceptedRoles);
-            }
-        });
-        return Map.copyOf(tmpRolesByIssuer);
-    }
-
-    @Bean
-    public JwtAuthenticationConverterFactory jwtAuthenticationConverterFactory(@Value("${config.rest.security.principal-claim}") String principalClaim) {
-        return new JwtAuthenticationConverterFactory(jwtProviderProperties.getProviders(), principalClaim, jwtProviderUtils);
+    public JwtAuthenticationConverterFactory jwtAuthenticationConverterFactory(@Value("${config.rest.security.principal-claim}") String principalClaim,
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/web/security/SecurityConfiguration.java]: The jwtAuthenticationConverterFactory method declares a parameter Map<String, Set<String>> allowedRolesByIssuer that is never used in the method body. More critically, the @Bean method that previously provided allowedRolesByIssuer was deleted in this same commit. Spring will fail at startup because it cannot inject this non-existent bean into the method parameter.

pls test this PR locally or on review env

File: src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+
+@Slf4j
+public class MultiIssuerJwtAuthenticationConverter implements Converter<Jwt, AbstractAuthenticationToken> {
+
+    private Converter<Jwt, Collection<GrantedAuthority>> jwtGrantedAuthoritiesConverter = new JwtGrantedAuthoritiesConverter();
+    private String principalClaimName = JwtClaimNames.SUB;
+    private final Set<String> emailClaims = new LinkedHashSet<>();
+    private final Set<String> allowedRoles;
+    private static final String DEFAULT_CLAIMS_EMAIL_KEY = "unique_name";
+    private static final String CLAIMS_EMAIL_KEY = System.getenv().getOrDefault("CLAIMS_EMAIL_KEY", DEFAULT_CLAIMS_EMAIL_KEY);
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java]: CLAIMS_EMAIL_KEY never used. DEFAULT_CLAIMS_EMAIL_KEY used at line 37 instead. add test case

File: src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+                .map(UserSecurityDetails::new)
+                .orElseGet(() -> new UserSecurityDetails(null));
+
+        JwtAuthenticationToken authToken =
+                filtered.isEmpty()
+                        ? new JwtAuthenticationToken(jwt)
+                        : new JwtAuthenticationToken(jwt, filtered, principalClaimValue);
+
+        if (filtered.isEmpty()) {
+            log.trace("Authorization state - token: {}, issuer: {}, authenticationToken: {},allowedRolesForIssuer: {}, authorities: {}",
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java]: was warn previously. what reason to change it to trace?

File: src/main/java/com/epam/aidial/cfg/web/security/SecurityConfiguration.java (hunk 3 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/web/security/SecurityConfiguration.java]: Thank you for the feedback.

The functionality of the PR was tested locally before publication. Spring does not fail because Map<String, Set<String>> is treated as a collection injection.
When no beans of value type are present, Spring injects an empty map by design.

File: src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java (hunk 1 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java]: The method implementation is repeated from JwtAuthenticationConverter.
We cannot extend JwtAuthenticationConverter because its convert method is final.
Therefore, this class implements its own conversion logic while preserving the original behavior.

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/security/SecurityClaimsExtractor.java [hunk 6]
```diff
@@ -46,13 +31,11 @@ public static String getEmail() {
...
         if (context.getAuthentication() instanceof JwtAuthenticationToken jwtAuthenticationToken) {
-            Jwt token = jwtAuthenticationToken.getToken();
-            log.trace("token claims: {}", token.getClaims());
-            Object uniqueName = token.getClaims().get(CLAIMS_EMAIL_KEY);
-            if (uniqueName != null) {
-                return Objects.toString(uniqueName);
+            if (jwtAuthenticationToken.getDetails() instanceof UserSecurityDetails details) {
+                return details.email();
             }
+            return null;
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/security/SecurityClaimsExtractor.java]: Looks like redundant return

File: docs/configuration.md (hunk 2 above)
Comment (KirylKurnosenka) [reply docs/configuration.md]: shouldn't it be providers.*.**email**-claims?

File: docs/configuration.md [hunk 7]
```diff
@@ -110,6 +110,7 @@ Additional Kubernetes client configuration options are available from the [Fabri
 | config.rest.security.default.allowedRoles          | -                             | ConfigAdmin,admin | No (recommended to adjust for target environment) | config.rest.security.mode=oidc | Comma-separated list of roles with access permissions |
 | config.rest.security.principal-claim               | SECURITY_USER_CLAIM           | oid               | No (recommended to adjust for target environment) | config.rest.security.mode=oidc | JWT claim name for user identification                |
 | config.rest.security.disable-swagger-authorization | DISABLE_SWAGGER_AUTHORIZATION | false             | No                                                | config.rest.security.mode=oidc | Disable authorization for Swagger UI                  |
+| config.rest.security.default.email.claims          | CLAIMS_EMAIL_KEY              | unique_name       | No                                                | config.rest.security.mode=oidc | Default JWT claim path used to extract user email     |
```
Comment (KirylKurnosenka) [inline docs/configuration.md]: I'd suggest to put defaults together for better visibility

File: src/main/resources/application.properties [hunk 8]
```diff
@@ -68,6 +68,7 @@ config.rest.security.mode=${CONFIG_REST_SECURITY_MODE:none}
 config.rest.security.default.allowedRoles=ConfigAdmin,admin
 config.rest.security.principal-claim=${SECURITY_USER_CLAIM:oid}
 config.rest.security.disable-swagger-authorization=${DISABLE_SWAGGER_AUTHORIZATION:false}
+config.rest.security.default.email.claims=${CLAIMS_EMAIL_KEY:unique_name}
```
Comment (KirylKurnosenka) [inline src/main/resources/application.properties]: I'd suggest to put defaults together for better visibility

File: src/main/java/com/epam/aidial/cfg/web/security/SecurityConfiguration.java [hunk 9]
```diff
@@ -42,25 +36,9 @@ public class SecurityConfiguration {
...
+                                                                               @Value("${config.rest.security.default.email.claims}") String defaultClaimsEmailKey) {
+        return new JwtAuthenticationConverterFactory(jwtProviderProperties.getProviders(), principalClaim, jwtProviderUtils, defaultAllowedRoles, defaultClaimsEmailKey);
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/SecurityConfiguration.java]: As far as I see `defaultAllowedRoles` is no longer needed to be class field

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/web/security/SecurityConfiguration.java (hunk 3 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/web/security/SecurityConfiguration.java]: done

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java [hunk 10]
```diff
@@ -0,0 +1,86 @@
...
+    private final Set<String> allowedRoles;
+
+    public MultiIssuerJwtAuthenticationConverter(List<String> issuerEmailClaims, Set<String> allowedRoles, String defaultClaimsEmailKey) {
+        this.allowedRoles = allowedRoles;
+
+        if (!CollectionUtils.isEmpty(issuerEmailClaims)) {
+            emailClaims.addAll(issuerEmailClaims);
+        }
+        if (StringUtils.isNotBlank(defaultClaimsEmailKey)) {
+            emailClaims.add(defaultClaimsEmailKey);
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java]: i'm not sure if we want to use default claims if issuerEmailClaims was specified. do you understand why it could be useful?

File: src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java [hunk 11]
```diff
@@ -0,0 +1,86 @@
...
+        var filtered = authorities.stream()
+                .map(GrantedAuthority::getAuthority)
+                .filter(allowedRoles::contains)
+                .map(SimpleGrantedAuthority::new)
+                .toList();
+
+        UserSecurityDetails details = JwtProviderUtils
+                .extractFirstClaim(jwt, List.copyOf(emailClaims))
+                .map(UserSecurityDetails::new)
+                .orElseGet(() -> new UserSecurityDetails(null));
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java]: may be better throw ex here? or add feature flag which control behaviour for undetected email claim case?

File: src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java [hunk 12]
```diff
@@ -0,0 +1,86 @@
...
+
+        JwtAuthenticationToken authToken =
+                filtered.isEmpty()
+                        ? new JwtAuthenticationToken(jwt)
+                        : new JwtAuthenticationToken(jwt, filtered, principalClaimValue);
+
+        if (filtered.isEmpty()) {
+            log.warn("Authorization state - token: {}, issuer: {}, authenticationToken: {},allowedRolesForIssuer: {}, authorities: {}",
+                    jwt, issuer, authToken, allowedRoles, authToken.getAuthorities());
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java]: authToken.getAuthorities() is always empty here. original authorities can be more useful here

Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java]: jwt and authtoken can contain sensitive information. and can be logged only in debug/trace level. pls mask them or remove from warn

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java (hunk 10 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java]: Default claim is kept as a fallback in case email is not found in issuer-specific claims.

File: src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java (hunk 11 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java]: Added feature flag

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java (hunk 10 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java]: but what a usecase? if i provide some specific claim for my provider I'd be surprised if system will try to use default one as fallback. usually such specific overrides assume full override of default value. isn't it?

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by KirylKurnosenka** [comment]
Please do not merge till GCP auth is done

File: src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java [hunk 13]
```diff
@@ -0,0 +1,92 @@
...
+import org.springframework.util.Assert;
+import org.springframework.util.CollectionUtils;
+
+import java.util.Collection;
+import java.util.LinkedHashSet;
+import java.util.List;
+import java.util.Set;
+
+@Slf4j
+public class MultiIssuerJwtAuthenticationConverter implements Converter<Jwt, AbstractAuthenticationToken> {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java]: Why is it called MultiIssuer if it works with single issuer?

File: src/main/java/com/epam/aidial/cfg/web/security/JwtProviderUtils.java [hunk 14]
```diff
@@ -44,4 +48,14 @@ private boolean isValidUrlWithProtocol(final String urlString) {
             return false;
         }
     }
+
+    public static Optional<String> extractFirstClaim(Jwt jwt, List<String> claims) {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/JwtProviderUtils.java]: It looks a bit strange to have static method in `@Component`

File: src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java [hunk 15]
```diff
@@ -0,0 +1,92 @@
...
+        var principalClaimValue = jwt.getClaimAsString(this.principalClaimName);
+        var filtered = authorities.stream()
+                .map(GrantedAuthority::getAuthority)
+                .filter(allowedRoles::contains)
+                .map(SimpleGrantedAuthority::new)
+                .toList();
+
+        var email = JwtProviderUtils.extractFirstClaim(jwt, List.copyOf(emailClaims));
+
+        if (requireEmail && email.isEmpty()) {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java]: I think it can be done at the very beggining

File: src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java [hunk 16]
```diff
@@ -0,0 +1,92 @@
...
+            throw new IllegalStateException("Email claim is required");
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java]: Should it be IllegalStateException?

File: src/main/java/com/epam/aidial/cfg/web/security/JwtProvidersProperties.java [hunk 17]
```diff
@@ -29,6 +29,7 @@ public static class ProviderConfig {
         private List<String> audiences;
         private List<String> aliases;
         private List<String> roleClaims;
+        private List<String> emailClaims;
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/JwtProvidersProperties.java]: As far as I see according to implementation we loop through `emailClaims` and get first claim with non-empty value.
Are there tokens with different structure (one token with email in `email1Claim`, second token with email in `email2Claim`, etc) for the same provider, so that I should set `emailClaims=email1Claim,email2Claim`? 
CC @siarhei-fedziukovich

File: src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java [hunk 18]
```diff
@@ -0,0 +1,92 @@
...
+        authToken.setDetails(details);
+        log.trace("Authorization state - token: {}, issuer: {}, authenticationToken: {},allowedRolesForIssuer: {}, authorities: {}",
+                jwt, issuer, authToken, allowedRoles, authorities);
+
+        return authToken;
+    }
+
+    public void setJwtGrantedAuthoritiesConverter(
+            Converter<Jwt, Collection<GrantedAuthority>> jwtGrantedAuthoritiesConverter) {
+        Assert.notNull(jwtGrantedAuthoritiesConverter, "jwtGrantedAuthoritiesConverter cannot be null");
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/MultiIssuerJwtAuthenticationConverter.java]: Can't we accept jwtGrantedAuthoritiesConverter and principalClaimName via constructor?

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/web/security/JwtProvidersProperties.java (hunk 17 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/web/security/JwtProvidersProperties.java]: i didn't met such tokens (different structure inside single IDP). but it doesn't mean that they are not exists

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/resources/application.properties [hunk 19]
```diff
@@ -86,8 +88,6 @@ core.applications.metadata.default.limit=${CORE_APPLICATIONS_METADATA_DEFAULT_LI
 core.toolsets.metadata.default.limit=${CORE_TOOLSETS_METADATA_DEFAULT_LIMIT:256}
 
 # Auth token provider configuration to interact with the DIAL Core
-core.auth.method=${CORE_AUTH_METHOD:token}
```
Comment (siarhei-fedziukovich) [inline src/main/resources/application.properties:89]: what reason for removal this properties?

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/web/security/ConfigurableJwtAuthenticationConverter.java [hunk 20]
```diff
@@ -0,0 +1,89 @@
...
+
+import java.util.Collection;
+import java.util.LinkedHashSet;
+import java.util.List;
+import java.util.Set;
+
+@Slf4j
+public class ConfigurableJwtAuthenticationConverter implements Converter<Jwt, AbstractAuthenticationToken> {
+
+    private Converter<Jwt, Collection<GrantedAuthority>> jwtGrantedAuthoritiesConverter = new JwtGrantedAuthoritiesConverter();
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/ConfigurableJwtAuthenticationConverter.java]: Looks like redundant assigment, since in constructor we assign incoming value. Also can be marked as final

File: src/main/java/com/epam/aidial/cfg/web/security/ConfigurableJwtAuthenticationConverter.java [hunk 21]
```diff
@@ -0,0 +1,89 @@
...
+import org.springframework.security.oauth2.server.resource.authentication.JwtGrantedAuthoritiesConverter;
+import org.springframework.util.CollectionUtils;
+
+import java.util.Collection;
+import java.util.LinkedHashSet;
+import java.util.List;
+import java.util.Set;
+
+@Slf4j
+public class ConfigurableJwtAuthenticationConverter implements Converter<Jwt, AbstractAuthenticationToken> {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/ConfigurableJwtAuthenticationConverter.java]: Didn't catch what "Configurable" word should highlight? Almost everything that has state can be "configurable". Can it be named just JwtAuthenticationConverter?

File: src/main/java/com/epam/aidial/cfg/web/security/ConfigurableJwtAuthenticationConverter.java [hunk 22]
```diff
@@ -0,0 +1,89 @@
...
+                                                  String defaultClaimsEmailKey,
+                                                  boolean requireEmail,
+                                                  IdentityProviderUtils identityProviderUtils,
+                                                  Converter<Jwt, Collection<GrantedAuthority>> jwtGrantedAuthoritiesConverter,
+                                                  String principalClaimName) {
+        this.allowedRoles = allowedRoles;
+        this.requireEmail = requireEmail;
+        this.identityProviderUtils = identityProviderUtils;
+        this.principalClaimName =
+                StringUtils.defaultIfBlank(principalClaimName, JwtClaimNames.SUB);
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/ConfigurableJwtAuthenticationConverter.java]: default should be value from "config.rest.security.principal-claim" property

File: src/main/java/com/epam/aidial/cfg/web/security/OpaqueAuthenticationConverterFactory.java [hunk 23]
```diff
@@ -0,0 +1,53 @@
...
+        return new ConfigurableOpaqueAuthenticationConverter(
+                config.getEmailClaims(),
+                getAllowedRoles(config.getAllowedRoles()),
+                defaultClaimsEmailKey,
+                requireEmail,
+                identityProviderUtils
+        );
+    }
+
+    private Set<String> getAllowedRoles(Set<String> allowedRoles) {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/OpaqueAuthenticationConverterFactory.java]: Code duplicate

File: src/main/java/com/epam/aidial/cfg/web/security/IdentityProviderUtils.java [hunk 24]
```diff
@@ -45,4 +50,16 @@ private boolean isValidUrlWithProtocol(final String urlString) {
             return false;
         }
     }
+
+    public Optional<String> extractFirstClaim(Map<String, Object> attributes,
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/IdentityProviderUtils.java]: Looks like the method has nothing common with claims and identity providers
It works with just Map and List, it can be moved to some MapUtils class or similar

File: src/main/java/com/epam/aidial/cfg/web/security/IdentityProviderUtils.java [hunk 25]
```diff
@@ -45,4 +50,16 @@ private boolean isValidUrlWithProtocol(final String urlString) {
...
+                                              List<String> claims) {
+        if (MapUtils.isEmpty(attributes) || CollectionUtils.isEmpty(claims)) {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/IdentityProviderUtils.java]: What I think can be here instead of this method is `getAllowedRoles` method

File: src/main/java/com/epam/aidial/cfg/web/security/OpaqueAuthenticationConverterFactory.java [hunk 26]
```diff
@@ -0,0 +1,53 @@
...
+
+    public OpaqueAuthenticationConverterFactory(List<OpaqueTokenProviderConfig> providers,
+                                                IdentityProviderUtils identityProviderUtils,
+                                                Set<String> defaultAllowedRoles,
+                                                String defaultClaimsEmailKey,
+                                                boolean requireEmail) {
+        this.defaultClaimsEmailKey = defaultClaimsEmailKey;
+        this.identityProviderUtils = identityProviderUtils;
+        this.defaultAllowedRoles = defaultAllowedRoles;
+        Map<String, ConfigurableOpaqueAuthenticationConverter> tmpConvertersByIssuer = new HashMap<>();
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/OpaqueAuthenticationConverterFactory.java]: That's not `byIssuer` as in jwt, that's `byProviderName`

File: src/main/java/com/epam/aidial/cfg/web/security/ConfigurableOpaqueAuthenticationConverter.java [hunk 27]
```diff
@@ -0,0 +1,77 @@
...
+        }
+    }
+
+    @Override
+    public Authentication convert(String introspectedToken, OAuth2AuthenticatedPrincipal authenticatedPrincipal) {
+        var providerName = (String) authenticatedPrincipal.getAttribute(OpaqueTokenProviderConfig.IDP_CLAIM);
+
+        var accessToken = new OAuth2AccessToken(OAuth2AccessToken.TokenType.BEARER, introspectedToken, null, null);
+
+        var email = identityProviderUtils.extractFirstClaim(authenticatedPrincipal.getAttributes(), List.copyOf(emailClaims));
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/ConfigurableOpaqueAuthenticationConverter.java]: We also need to extract email the same way here com/epam/aidial/cfg/web/security/OpaqueTokenCustomGrantedAuthoritiesConverters.java:47

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/web/security/ConfigurableOpaqueAuthenticationConverter.java (hunk 27 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/web/security/ConfigurableOpaqueAuthenticationConverter.java]: For opaque tokens, extracting the email and setting UserSecurityDetails in the converter is appropriate, since the introspector only provides attributes and Authentication has no details by default. This keeps role filtering and user info setup consistent and secure.

File: src/main/java/com/epam/aidial/cfg/utils/MapExtractionUtils.java [hunk 28]
```diff
@@ -0,0 +1,29 @@
...
+import java.util.Optional;
+
+@UtilityClass
+public final class MapExtractionUtils {
+
+    public static Optional<String> extractFirstPresentValue(
+            Map<String, ?> source,
+            List<String> keys) {
+
+        if (MapUtils.isEmpty(source) || keys == null || CollectionUtils.isEmpty(keys)) {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/utils/MapExtractionUtils.java]: `CollectionUtils.isEmpty` already have `keys == null` check

File: src/main/java/com/epam/aidial/cfg/utils/MapExtractionUtils.java [hunk 29]
```diff
@@ -0,0 +1,29 @@
...
+
+import java.util.List;
+import java.util.Map;
+import java.util.Objects;
+import java.util.Optional;
+
+@UtilityClass
+public final class MapExtractionUtils {
+
+    public static Optional<String> extractFirstPresentValue(
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/utils/MapExtractionUtils.java]: I'd suggest to name extractFirstNonNullValue, since you can have entry like ("some-key", null), so the value is present, but empty optional is returned
Also can we have method more generic and return not `Optional<String>`, but Optional parameterized with map value type?

File: src/main/java/com/epam/aidial/cfg/web/security/IdentityProviderUtils.java [hunk 30]
```diff
@@ -16,6 +17,13 @@ public class IdentityProviderUtils {
     private static final String V1_ISSUER_FORMAT = "https://%s/%s/";
     private static final String V2_ISSUER_FORMAT = "https://%s/%s/v2.0";
 
+    private final Set<String> defaultAllowedRoles;
+
+    public IdentityProviderUtils(@Value("${config.rest.security.default.allowedRoles}")
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/web/security/IdentityProviderUtils.java]: Could it be on single line? Otherwise it a bit confuses and seems that there are 2 constructor args

Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/web/security/IdentityProviderUtils.java]: updated

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/web/security/ConfigurableOpaqueAuthenticationConverter.java (hunk 27 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/web/security/ConfigurableOpaqueAuthenticationConverter.java]: updated

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/utils/MapExtractionUtils.java (hunk 29 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/utils/MapExtractionUtils.java]: 2nd part is still relevant. I'm suggesting to parameterize method
```
public static <K, V> Optional<V> extractFirstNonNullValue(Map<K,V> map, List<K> keys) {
...

}
```

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/utils/MapExtractionUtils.java (hunk 29 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/utils/MapExtractionUtils.java]: done

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by KirylKurnosenka — APPROVED** [review]
