### PR TITLE
fix: improve Influx3 query engine correctness and stability

### LINKED ISSUE #744: Add Admin Backend Support for Reading Telemetry Data from InfluxDB 3
### Name and Version

0.16.0

### What is the problem this feature will solve?

Our admin backend currently supports reading telemetry data only from InfluxDB 1.x and 2.x. As we migrate or deploy new environments using InfluxDB 3, the admin tools cannot access, query, or display telemetry stored there. This leads to:
* Inability for admins to monitor and analyze telemetry in InfluxDB 3–backed environments
* Additional operational overhead and manual workarounds to inspect telemetry in InfluxDB 3
Without native InfluxDB 3 support, we cannot fully adopt or standardize on the latest InfluxDB version for telemetry.

### What is the feature you are proposing to solve the problem?

Extend the admin backend to natively read telemetry data from InfluxDB 3, alongside existing support for InfluxDB 1 and 2. Specifically:
* Add configuration options to enable InfluxDB 3 as a telemetry data source (including connection details, authentication, and database/bucket selection)
* Implement a data access layer/adapter for InfluxDB 3 that:
** Supports the existing query patterns used by the admin UI (time-range queries, filtering, aggregation, etc.)
** Normalizes responses to the same internal telemetry model used today for InfluxDB 1/2
* Update any feature flags, environment variables, or service discovery logic so the admin backend can select the correct InfluxDB version per environment
* Add tests (unit + integration where possible) to verify:
** Correct connectivity and authentication to InfluxDB 3
** Query compatibility and result shape parity with InfluxDB 1/2
** Backwards compatibility for existing InfluxDB 1/2 deployments
* Provide minimal documentation/config examples for operators describing how to configure the admin backend to use InfluxDB 3

Outcome: Admin users can seamlessly view and query telemetry from InfluxDB 3 in the same way they currently do for InfluxDB 1/2, without changing the admin UI or workflows.

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by oleksii-donets**
### Applicable issues

- fixes #744

### Description of changes

- **fix: time alias breaks window aggregation** — Window aggregation queries in Influx3 (SQL) now use a temporary column alias instead of the user-facing name (e.g. `time`), preventing collisions with InfluxDB's reserved `time` column that broke `GROUP BY` / `ORDER BY` clauses.
- **fix: preserve null values in JSON API response** — `MetricController.toDataDto` no longer stringifies `null` to `"null"`; actual `null` values are passed through to the JSON response.
- **fix: normalize ungrouped aggregation nulls to zeros in Influx3Engine** — When an ungrouped aggregation query returns no rows or rows with null aggregation values (e.g. `sum` over zero matching records), the engine now returns `0` / `0.0` instead of null or an empty result, matching Flux behavior.
- **chore: refactoring** — Moved sort-resolution logic (`resolveOrderByColumnName`) from `SqlQueryBuilder` up to `AbstractQueryBuilder` so both Flux and SQL builders share the same alias-aware resolution. Renamed `aliasToExpression` → `nameToExpression` and consolidated alias/column registration into `resolveExpressionsToOuterColumnNames`. `SimpleFluxBuilder.createSortPart` simplified to accept pre-resolved column names. `LocalDateTime` values from Influx3 are normalized to `Instant` (UTC).

### Checklist

- [X] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java [hunk 1]
```diff
@@ -395,6 +399,28 @@ protected FluxQueryContext buildWindowColumnAggregationQuery(Query query) {
                 .build();
     }
 
+    private String buildSortPart(List<Sort> orderBy) {
+        if (CollectionUtils.isEmpty(orderBy)) {
+            return "";
+        }
+
+        var direction = orderBy.stream().map(Sort::getDirection).distinct()
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java:407]: Does that mean that flux supports only single direction for all columns?

Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java:407]: I see that's just copied from other class

**Review by KirylKurnosenka — APPROVED** [review]
