### PR TITLE
fix: #371 fix SAST issues

### LINKED ISSUE #371: [Tech Debt] Review SAST vulnerabilities and fix if exists
### Name and Version

0.10.0

### What steps will reproduce the bug?

review SAST report

### What is the expected behavior?

no vulnerabilities in SAST report

### What do you see instead?

-

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by siarhei-fedziukovich**
### Applicable issues

- fixes #371

### Description of changes

* path traversal in DialResources zip export (reports 960/961/962)
* prevent HTTP response splitting attacks in CorrelationIdInterceptor (report 959)

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/configuration/logging/CorrelationIdInterceptor.java [hunk 1]
```diff
@@ -34,6 +35,7 @@ public void afterCompletion(final HttpServletRequest request, final HttpServletR
 
     private String resolveValidCorrelationId(final HttpServletRequest request) {
         var correlationId = request.getHeader(CORRELATION_ID_HEADER_NAME);
+        correlationId = HeaderUtils.sanitizeHeaderValue(correlationId);
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/configuration/logging/CorrelationIdInterceptor.java:38]: Doesn't pattern below already handle \r\n within correlationId?

File: src/main/java/com/epam/aidial/cfg/utils/PathUtils.java [hunk 2]
```diff
@@ -63,12 +60,7 @@ public static VersionedPathParts parseVersionedPath(String path) {
         var rawName = path.substring(lastSlashIndex + 1);
         var nameAndVersion = extractNameAndVersion(rawName);
 
-        return VersionedPathParts.builder()
-                .path(path)
-                .folderId(folderId)
-                .name(nameAndVersion.getLeft())
-                .version(nameAndVersion.getRight())
-                .build();
+        return VersionedPathParts.builder().path(path).folderId(folderId).name(nameAndVersion.getLeft()).version(nameAndVersion.getRight()).build();
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/utils/PathUtils.java]: Is such change needed?

File: src/test/java/com/epam/aidial/cfg/configuration/logging/CorrelationIdInterceptorTest.java [hunk 3]
```diff
@@ -0,0 +1,133 @@
...
+        MDC.clear();
+    }
+
+    @AfterEach
+    void tearDown() {
+        MDC.clear();
+    }
+
+    @Test
+    void testPreHandle_withValidCorrelationId() {
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/configuration/logging/CorrelationIdInterceptorTest.java]: This test and the test below are the same. It can be parameterized with `validCorrelationId`

File: src/test/java/com/epam/aidial/cfg/configuration/logging/CorrelationIdInterceptorTest.java [hunk 4]
```diff
@@ -0,0 +1,133 @@
...
+
+        // then
+        assertThat(result).isTrue();
+        assertThat(response.getHeader(CorrelationIdInterceptor.CORRELATION_ID_HEADER_NAME))
+                .isEqualTo(validCorrelationId);
+        assertThat(MDC.get("_correlation_id")).isEqualTo(validCorrelationId);
+    }
+
+    @Test
+    void testPreHandle_withInvalidCorrelationId_tooShort() {
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/configuration/logging/CorrelationIdInterceptorTest.java]: The same: this test and test below can be combined into single one

File: src/main/java/com/epam/aidial/cfg/service/prompt/ZipPromptEximService.java [hunk 5]
```diff
@@ -79,11 +79,21 @@ public ImportResourcesFileResult importPrompts(ImportResources importPrompts, Mu
             ZipEntry zipEntry;
             var promptsEximDtos = new HashMap<String, PromptsEximDto>();
             while ((zipEntry = zipInputStream.getNextEntry()) != null) {
-                if (zipEntry.getName().startsWith(PROMPTS_FOLDER) && zipEntry.getName().endsWith(JSON_FILE_EXTENSION)) {
-                    promptsEximDtos.put(zipEntry.getName(), jsonMapper.readValue(zipInputStream, PromptsEximDto.class));
+                var zipEntryName = zipEntry.getName();
+                
+                // Validate zip entry path to prevent path traversal attacks
+                try {
+                    zipEntryName = PathUtils.validateZipEntryPath(zipEntryName);
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/service/prompt/ZipPromptEximService.java:86]: Could you please clarify how `zipEntryName` can equal to any of the values mentioned in `PathUtilsTest` in `invalidZipEntryPaths` method?

File: src/main/java/com/epam/aidial/cfg/configuration/logging/CorrelationIdInterceptor.java (hunk 1 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/configuration/logging/CorrelationIdInterceptor.java:38]: actually it will. but let's make SAST happy. (and defense in depth)

File: src/main/java/com/epam/aidial/cfg/service/prompt/ZipPromptEximService.java (hunk 5 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/service/prompt/ZipPromptEximService.java:86]: https://medium.com/@contactomyna/securing-zip-file-operations-understanding-and-preventing-path-traversal-attacks-74d79f696c46

File: src/main/java/com/epam/aidial/cfg/utils/PathUtils.java (hunk 2 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/utils/PathUtils.java]: autoformatting using out codestyle rules.

Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/utils/PathUtils.java]: Well, looks like I don't have such rules. Also it seems that with such formatting line becomes too long

File: src/test/java/com/epam/aidial/cfg/configuration/logging/CorrelationIdInterceptorTest.java (hunk 3 above)
Comment (siarhei-fedziukovich) [reply src/test/java/com/epam/aidial/cfg/configuration/logging/CorrelationIdInterceptorTest.java]: changed

File: src/test/java/com/epam/aidial/cfg/configuration/logging/CorrelationIdInterceptorTest.java (hunk 4 above)
Comment (siarhei-fedziukovich) [reply src/test/java/com/epam/aidial/cfg/configuration/logging/CorrelationIdInterceptorTest.java]: changed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/test/java/com/epam/aidial/cfg/utils/PathUtilsTest.java [hunk 6]
```diff
@@ -0,0 +1,143 @@
...
+class PathUtilsTest {
+
+    @ParameterizedTest
+    @MethodSource("validZipEntryPaths")
+    void testValidateZipEntryPath_ValidPaths_ShouldNotThrow(String zipEntryPath) {
+        // given
+        // when & then
+        assertThat(PathUtils.validateZipEntryPath(zipEntryPath))
+                .isNotNull()
+                .isNotEmpty();
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/utils/PathUtilsTest.java]: Don't we know expected result for incoming params?

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/test/java/com/epam/aidial/cfg/utils/PathUtilsTest.java (hunk 6 above)
Comment (siarhei-fedziukovich) [reply src/test/java/com/epam/aidial/cfg/utils/PathUtilsTest.java]: expected values was added

File: src/main/java/com/epam/aidial/cfg/utils/PathUtils.java (hunk 2 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/utils/PathUtils.java]: reverted

**Review by KirylKurnosenka — APPROVED** [review]
