### PR TITLE
fix: wrap interaction with kubernetes client into separate thread with operation timeout

### LINKED ISSUE #248: [Export Config] Scheduled export stucks at writing into config map
### Name and Version

ai-dial-admin-backed

### What steps will reproduce the bug?

No specific steps to reproduce.
Sometimes "scheduling-x" thread stucks when writing config into Kubernetes config map

### What is the expected behavior?

Request to write into config map should be timed out

### What do you see instead?

Request to write into config map hangs infinitely

### Additional information

Thread dump
```
"scheduling-1" - Thread t@70
   java.lang.Thread.State: WAITING
        at java.base@17.0.16/jdk.internal.misc.Unsafe.park(Native Method)
        - parking to wait for <34dc8971> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.base@17.0.16/java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.base@17.0.16/java.util.concurrent.CompletableFuture$Signaller.block(Unknown Source)
        at java.base@17.0.16/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
        at java.base@17.0.16/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
        at java.base@17.0.16/java.util.concurrent.CompletableFuture.waitingGet(Unknown Source)
        at java.base@17.0.16/java.util.concurrent.CompletableFuture.get(Unknown Source)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:491)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:524)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleGet(OperationSupport.java:467)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleGet(BaseOperation.java:792)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.requireFromServer(BaseOperation.java:193)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.getItemOrRequireFromServer(BaseOperation.java:176)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.edit(HasMetadataOperation.java:93)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.edit(BaseOperation.java:216)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.edit(BaseOperation.java:98)
        at com.epam.aidial.cfg.service.impl.storage.K8ConfigService.updateConfigMapEntry(K8ConfigService.java:52)
        at com.epam.aidial.cfg.service.impl.storage.ConfigSourceConfigMap.lambda$setSource$2(ConfigSourceConfigMap.java:47)
        at com.epam.aidial.cfg.service.impl.storage.ConfigSourceConfigMap$$Lambda$2924/0x00007fd150200c40.apply(Unknown Source)
        at com.epam.aidial.cfg.service.impl.storage.K8ConfigService.withClient(K8ConfigService.java:28)
        at com.epam.aidial.cfg.service.impl.storage.ConfigSourceConfigMap.setSource(ConfigSourceConfigMap.java:46)
        at com.epam.aidial.cfg.service.impl.storage.CompositeConfigSource.writeConfig(CompositeConfigSource.java:55)
        at com.epam.aidial.cfg.service.export.ConfigExportServiceSecuredImpl.lambda$export$0(ConfigExportServiceSecuredImpl.java:31)
        at com.epam.aidial.cfg.service.export.ConfigExportServiceSecuredImpl$$Lambda$2917/0x00007fd1501e08d8.run(Unknown Source)
        at com.epam.aidial.cfg.service.transfer.ConfigTransferLock.withWriteLock(ConfigTransferLock.java:28)
        at com.epam.aidial.cfg.service.export.ConfigExportServiceSecuredImpl.export(ConfigExportServiceSecuredImpl.java:30)
        at com.epam.aidial.cfg.service.export.ConfigExportFacade.exportCurrentConfig(ConfigExportFacade.java:37)
        at jdk.internal.reflect.GeneratedMethodAccessor433.invoke(Unknown Source)
        at java.base@17.0.16/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base@17.0.16/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.AbstractTraceInterceptor.invoke(AbstractTraceInterceptor.java:135)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:173)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:728)
        at com.epam.aidial.cfg.service.export.ConfigExportFacade$$SpringCGLIB$$0.exportCurrentConfig(<generated>)
        at com.epam.aidial.cfg.service.export.ConfigExportScheduler.exportCurrentConfig(ConfigExportScheduler.java:36)
        at jdk.internal.reflect.GeneratedMethodAccessor412.invoke(Unknown Source)
        at java.base@17.0.16/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base@17.0.16/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.AbstractTraceInterceptor.invoke(AbstractTraceInterceptor.java:135)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:173)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:728)
        at com.epam.aidial.cfg.service.export.ConfigExportScheduler$$SpringCGLIB$$0.exportCurrentConfig(<generated>)
        at jdk.internal.reflect.GeneratedMethodAccessor412.invoke(Unknown Source)
        at java.base@17.0.16/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base@17.0.16/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124)
        at org.springframework.scheduling.support.ScheduledMethodRunnable$$Lambda$2627/0x00007fd150120cb8.run(Unknown Source)
        at io.micrometer.observation.Observation.observe(Observation.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124)
        at org.springframework.scheduling.config.Task$OutcomeTrackingRunnable.run(Task.java:85)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base@17.0.16/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base@17.0.16/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base@17.0.16/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base@17.0.16/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base@17.0.16/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base@17.0.16/java.lang.Thread.run(Unknown Source)

   Locked ownable synchronizers:
        - locked <24dad553> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)

        - locked <4eba05c0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

```

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #248 

### Description of changes
Used cached thread pool to operate with kubernetes client. The pool helps to interrupt operation which takes more time than limit defined via `kubernetes-config.client.operationTimeoutMs` app property.

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/configuration/ExportConfiguration.java [hunk 1]
```diff
@@ -90,7 +91,7 @@ public ConfigSourceKubeSecret configSourceJsonKubeSecret(VersionAwareFieldFilter
     @Bean
     @ConditionalOnExpression(("'${config.export.storageType}' == 'CONFIG_MAP' OR '${config.export.storageType}' == 'KUBE_SECRET'"))
     public K8ConfigService k8ConfigService(K8sProperties k8sProperties) {
-        return new K8ConfigService(k8sProperties);
+        return new K8ConfigService(k8sProperties, Executors.newCachedThreadPool());
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/configuration/ExportConfiguration.java]: i'd use ThreadFactory  with setNameFormat. it'll help to find threads from this pool in threaddumps

**Review by siarhei-fedziukovich — DISMISSED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/configuration/ExportConfiguration.java (hunk 1 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/configuration/ExportConfiguration.java]: adjusted

**Review by siarhei-fedziukovich — APPROVED** [review]
