### PR TITLE
fix: improve system rollback and activity audit

### LINKED ISSUE #595: [Audit/Activities]  Incorrect Audit Log behavior for deleted models and cloned entities with the Same ID.
### Name and Version

[FE]0.13.0-rc [BE]0.13.0-rc Core:[Default version]latest

### What steps will reproduce the bug?

1. Go to the **Entities → Models** section.  
2. Delete an existing model.  
3. Select another model and use the **Duplicate Model** action.  
4. In the duplication modal, give the new model the **ID** of the previously deleted model.  
5. Save the new duplicate model.  
6. Navigate to the **Audit→Activities** section for the new model.  
7. Observe that the activity log displays:  
   - A **Delete** action associated with the deleted model.  
   - An **Update** action instead of a **Create** action for the newly duplicated model.

### What is the expected behavior?

- The **Audit→Activities** section should correctly display:  
  - **Delete**, associated with the previously deleted model.  
  - **Create**, associated with the newly duplicated model with the reused ID.  
- The logs should logically follow the sequence of actions and clearly distinguish between entities.

### What do you see instead?

- The activity log incorrectly displays a **Delete** action followed by an **Update** action for the model with the reused ID.  
- This misrepresentation implies a modification of the deleted model, even though the **Create** action for the new entity is missing.

Image

### Additional information

_No response_

### LINKED ISSUE #684: [Audit->System Rollback] In Activities table you should see just relevant changes after System Rollback
### Name and Version

FE]0.14.0-rc [BE]0.14.0-rc

### What steps will reproduce the bug?

1. Go to DIAL Admin Panel
2. Update any entity (for example, add description to model)
3. Rollback to previous state via 'System Rollback' option
4. Go to Audit and open Activities menu

### What is the expected behavior?

In Activities table you should see just relevant changes

### What do you see instead?

Now, when one entity is updated, some set of entities with just the update date are added to the activity list

### Additional information

_No response_

### LINKED ISSUE #700: [Sync with core] Forward per Request Key Toggle does not synchronize changes with Core.
### Name and Version

 [FE]0.14.0-rc [BE]0.14.0-rc Core: [Default version]latest

### What steps will reproduce the bug?

1. Navigate to **Entities → Toolsets**.  
2. Open an existing **Toolset** or create a new **Toolset**.  
3. Toggle the **Forward per request key** option (turn it on or off).  
4. Observe that the **Sync with core** status changes to **Out Of Sync**.   
5. Modify any other field in the form (e.g., change a description, or add a new configuration).  
6. Click **Save** and wait for synchronization.  
7. Observe that the **Sync with core** status updates to **Sync** after saving unrelated changes.  
**NOTE: The same behavior is observed in the Authentication section and when editing Roles — synchronization with Core does not happen.**

### What is the expected behavior?

- Changing the state of the **Forward per request key** toggle should trigger synchronization with Core, updating the **Sync with core** status to **Sync** after the action is processed.  

### What do you see instead?

- Toggling the **Forward per request key** changes the **Sync with core** status to **Out Of Sync**, but the changes are not synchronized with Core.  
- The status only updates to **Sync** when an unrelated field is modified and saved. 
- The same behavior is observed in the Authentication section — synchronization with Core does not happen.

Image

Image

Image

 

### Additional information

_No response_

### LINKED ISSUE #743: [Sync State] Out of sync state after adding role to entity
### EPAM AI DIAL Admin version

[FE]0.15.0-rc [BE]0.15.0-rc

### How to reproduce

1. Open model with 'Sync' state 
2. Switch to 'Role' tab
3. Add role and save changes
4. Back to 'Properties' tab

### Actual result

Synchronization status with the core becomes 'Out of sync'

Image

### Expected result

Any changes must trigger a 'processing' state

### Additional information

_No response_

### Confidential information

- [x] I confirm that do not share any confidential information

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #684 
- fixes #700 
- fixes #595 
- fixes #743  

### Description of changes
Removed `createdAt` and `updatedAt` fields from historical data

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by KirylKurnosenka** [comment]
/deploy-review

>GitHub actions run: [22712879846](https://github.com/epam/ai-dial-ci/actions/runs/22712879846)

| Stage                        | Status         |
| ---------------------------- | -------------- |
| [deploy-review](https://chat-ai-dial-admin-backend-pr-732.gke.test.dial.parts) | [Success ✅](https://github.com/epam/ai-dial-ci/actions/runs/22712879846/job/65855052215) |
| chat | [Failed ❌](https://github.com/epam/ai-dial-ci/actions/runs/22712879846/job/65856198683) |

File: src/test/java/com/epam/aidial/cfg/functional/tests/history/RolesHistoryFunctionalTest.java [hunk 1]
```diff
@@ -188,6 +188,30 @@ public void shouldCorrectlyTrackKeyUpdatedAtInLatestAndAuditStatesWhenRoleIsCrea
...
+
+        RoleDto roleDto = createRoleDto("1");
+        roleDto.setLimits(Map.of(modelDto.getName(), limitDto));
+        roleFacade.createRole(roleDto);
+
+        Integer latestRevision = CollectionUtils.lastElement(historyFacade.getRevisionsList()).getId();
+
+        // verify
+        Assertions.assertEquals(Instant.ofEpochMilli(222L), modelFacade.getModel(modelDto.getName()).getUpdatedAt());
+        // todo fix
```
Comment (siarhei-fedziukovich) [inline src/test/java/com/epam/aidial/cfg/functional/tests/history/RolesHistoryFunctionalTest.java]: todo

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/test/java/com/epam/aidial/cfg/functional/tests/history/RolesHistoryFunctionalTest.java (hunk 1 above)
Comment (KirylKurnosenka) [reply src/test/java/com/epam/aidial/cfg/functional/tests/history/RolesHistoryFunctionalTest.java]: That "todo" was added for purpose.

**Comment by KirylKurnosenka** [comment]
/deploy-review

>GitHub actions run: [22773002215](https://github.com/epam/ai-dial-ci/actions/runs/22773002215)

| Stage                        | Status         |
| ---------------------------- | -------------- |
| [deploy-review](https://chat-ai-dial-admin-backend-pr-732.gke.test.dial.parts) | [Success ✅](https://github.com/epam/ai-dial-ci/actions/runs/22773002215/job/66058876268) |
| chat | [Success ✅](https://github.com/epam/ai-dial-ci/actions/runs/22773002215/job/66060250140) |

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by siarhei-fedziukovich — APPROVED** [review]

**Review by Katerina-Charakhovich — APPROVED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/test/java/com/epam/aidial/cfg/functional/tests/history/RolesHistoryFunctionalTest.java (hunk 1 above)
Comment (KirylKurnosenka) [reply src/test/java/com/epam/aidial/cfg/functional/tests/history/RolesHistoryFunctionalTest.java]: Removed
