### PR TITLE
fix: set correct interceptors_order for models and applications in regular and audit tables

### LINKED ISSUE #567: [Audit --> Activities] There is no data in the Current state and Rollback state
### Name and Version

Admin: [FE]0.13.0-rc [BE]0.13.0-rc

### What steps will reproduce the bug?

1. Open AI Dial Admin.
2.  Go to Audit --> Activities.
3. Click the System Rollback button.

### What is the expected behavior?

The "Current state" and "Rollback state" panels should display relevant resource information for each selected tab (Adapters).

### What do you see instead?

There is no information displayed in both the "Current state" and "Rollback state" panels. Instead, only the message "Resource does not exist" is shown in both sections on the Adapters tab.

Image

### Additional information

The problem is reproduced on uat env (Admin: [FE]0.12.4 [BE]0.12.0 Core:[Detected]0.39.1) and staging env (Admin: [FE]0.13.0-rc [BE]0.13.0-rc Core:[Default version]latest) just for Interceptor Templates

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #567

### Description of changes
In regular and audit tables set correct interceptors_order for models and applications which have several linked interceptors and interceptors_order = 0 for each interceptor

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/resources/db/migration/H2/V1.89__UpdateInterceptorsOrderInInterceptorModelRegularAndAuditTables.sql [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+    ROW_NUMBER() OVER (
+        PARTITION BY a.model_name
+        ORDER BY a.interceptor_name
+    ) - 1 AS new_order
+FROM interceptor_model a
+JOIN all_zero_groups g
+  ON a.model_name = g.model_name;
+
+-- Update interceptors_order in interceptor_model according to values from temporary interceptor_model_ranked table
+UPDATE interceptor_model t
```
Comment (siarhei-fedziukovich) [inline src/main/resources/db/migration/H2/V1.89__UpdateInterceptorsOrderInInterceptorModelRegularAndAuditTables.sql:26]: this statement will update all rows. there are no join/where clause. subquery returns null for rown which are not in interceptor_model_ranked.

File: src/main/resources/db/migration/H2/V1.89__UpdateInterceptorsOrderInInterceptorModelRegularAndAuditTables.sql [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+        PARTITION BY a.model_name, a.rev
+        ORDER BY a.interceptor_name
+    ) - 1 AS new_order
+FROM interceptor_model_aud a
+JOIN all_zero_groups g
+  ON a.model_name = g.model_name
+ AND a.rev = g.rev;
+
+-- Update interceptors_order in interceptor_model_aud according to values from temporary interceptor_model_aud_ranked table
+UPDATE interceptor_model_aud t
```
Comment (siarhei-fedziukovich) [inline src/main/resources/db/migration/H2/V1.89__UpdateInterceptorsOrderInInterceptorModelRegularAndAuditTables.sql:71]: this statement will update all rows. there are no join/where clause. subquery returns null for rown which are not in interceptor_model_aud_ranked .

File: src/main/resources/db/migration/H2/V1.90__UpdateInterceptorsOrderInInterceptorApplicationRegularAndAuditTables.sql [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+        PARTITION BY a.application_name
+        ORDER BY a.interceptor_name
+    ) - 1 AS new_order
+FROM interceptor_application a
+JOIN all_zero_groups g
+  ON a.application_name = g.application_name;
+
+-- Update interceptors_order in interceptor_application according to values from temporary interceptor_application_ranked table
+UPDATE interceptor_application t
+SET interceptors_order = (
```
Comment (siarhei-fedziukovich) [inline src/main/resources/db/migration/H2/V1.90__UpdateInterceptorsOrderInInterceptorApplicationRegularAndAuditTables.sql]: this statement will update all rows. there are no join/where clause. subquery returns null for rown which are not in interceptor_application_ranked .

File: src/main/resources/db/migration/H2/V1.90__UpdateInterceptorsOrderInInterceptorApplicationRegularAndAuditTables.sql [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+        PARTITION BY a.application_name, a.rev
+        ORDER BY a.interceptor_name
+    ) - 1 AS new_order
+FROM interceptor_application_aud a
+JOIN all_zero_groups g
+  ON a.application_name = g.application_name
+ AND a.rev = g.rev;
+
+-- Update interceptors_order in interceptor_application_aud according to values from temporary interceptor_application_aud_ranked table
+UPDATE interceptor_application_aud t
```
Comment (siarhei-fedziukovich) [inline src/main/resources/db/migration/H2/V1.90__UpdateInterceptorsOrderInInterceptorApplicationRegularAndAuditTables.sql:71]: this statement will update all rows. there are no join/where clause. subquery returns null for rown which are not in interceptor_application_aud_ranked .

File: src/main/resources/db/migration/H2/V1.89__UpdateInterceptorsOrderInInterceptorModelRegularAndAuditTables.sql (hunk 1 above)
Comment (KirylKurnosenka) [reply src/main/resources/db/migration/H2/V1.89__UpdateInterceptorsOrderInInterceptorModelRegularAndAuditTables.sql:26]: adjusted

File: src/main/resources/db/migration/H2/V1.89__UpdateInterceptorsOrderInInterceptorModelRegularAndAuditTables.sql (hunk 2 above)
Comment (KirylKurnosenka) [reply src/main/resources/db/migration/H2/V1.89__UpdateInterceptorsOrderInInterceptorModelRegularAndAuditTables.sql:71]: adjusted

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/resources/db/migration/H2/V1.90__UpdateInterceptorsOrderInInterceptorApplicationRegularAndAuditTables.sql (hunk 4 above)
Comment (KirylKurnosenka) [reply src/main/resources/db/migration/H2/V1.90__UpdateInterceptorsOrderInInterceptorApplicationRegularAndAuditTables.sql:71]: adjusted

File: src/main/resources/db/migration/H2/V1.90__UpdateInterceptorsOrderInInterceptorApplicationRegularAndAuditTables.sql (hunk 3 above)
Comment (KirylKurnosenka) [reply src/main/resources/db/migration/H2/V1.90__UpdateInterceptorsOrderInInterceptorApplicationRegularAndAuditTables.sql]: adjusted

**Review by siarhei-fedziukovich — DISMISSED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by siarhei-fedziukovich — APPROVED** [review]
