### PR TITLE
fix!: remove configurationEndpoint & add 'features' and 'default' [Interceptors]

### LINKED ISSUE #224: Interceptor `configurationEndpoint` and `defaults` properties does not supported in admin panel
### Name and Version

0.7.0

### What steps will reproduce the bug?

https://github.com/epam/ai-dial-core/blob/development/docs/dynamic-settings/interceptors.md
DIAL core support `configurationEndpoint` and `defaults` properties in interceptor.features. 

### What is the expected behavior?

_No response_

### What do you see instead?

support them

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Pasichniuk**
### Applicable issues

- fixes #224 

### Description of changes

Removed 'configurationEndpoint' from Interceptor (since it is present in Features). Added 'features' and 'defaults' properties to Interceptor.

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by siarhei-fedziukovich** [comment]
mark PR as breaking change

File: src/main/java/com/epam/aidial/cfg/domain/util/InterceptorEndpointResolver.java [hunk 1]
```diff
@@ -48,7 +51,8 @@ public void processContainerEndpoints(InterceptorEntity interceptorEntity) {
                 InterceptorContainerEntity::getConfigurationEndpointPath,
                 (entity, endpoints) -> {
                     entity.setEndpoint(endpoints[0]);
-                    entity.setConfigurationEndpoint(endpoints[1]);
+                    FeaturesEntity features = Optional.ofNullable(entity.getFeatures()).orElse(new FeaturesEntity());
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/domain/util/InterceptorEndpointResolver.java]: where new features set in parent interceptor? (created in .orElse(new FeaturesEntity());)

File: src/main/resources/db/migration/H2/V1.60__RemoveConfigEndpointAddDefaultsAndFeaturesToInterceptorTable.sql [hunk 2]
```diff
@@ -0,0 +1,49 @@
+-- add new fields to interceptor_entity table
+alter table if exists interceptor_entity drop column if exists configuration_endpoint;
```
Comment (KirylKurnosenka) [inline src/main/resources/db/migration/H2/V1.60__RemoveConfigEndpointAddDefaultsAndFeaturesToInterceptorTable.sql]: Do we really need to drop this column and then restore back?

**Comment by siarhei-fedziukovich** [comment]
Preparing review...

File: src/main/resources/db/migration/H2/V1.60__RemoveConfigEndpointAddDefaultsAndFeaturesToInterceptorTable.sql (hunk 2 above)
Comment (Pasichniuk) [reply src/main/resources/db/migration/H2/V1.60__RemoveConfigEndpointAddDefaultsAndFeaturesToInterceptorTable.sql]: Actually no, removed drop statement

File: src/main/java/com/epam/aidial/cfg/domain/util/InterceptorEndpointResolver.java (hunk 1 above)
Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/domain/util/InterceptorEndpointResolver.java]: Didn't get the question. Features are received in InterceptorDto, if not there are default value 'new FeaturesDto()'. This checks for null are just in case something will change, to avoid NPEs

**Comment by Pasichniuk** [comment]
Should be merged after #212 to avoid DB migration issues

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/service/transfer/exporter/InterceptorExporter.java [hunk 3]
```diff
@@ -59,17 +62,21 @@ private List<Interceptor> getInterceptorsWithRemovedDependencies(List<ExportConf
...
-        ) {
-            interceptor.setSource(null);
+    private Interceptor removeDependencies(Interceptor interceptor, Set<ExportConfigComponentType> componentTypes, ExportFormat exportFormat) {
+        if (interceptor.getSource() != null && interceptor.getSource() instanceof InterceptorRunnerSource runnerSource) {
+            if (exportFormat == ExportFormat.CORE) {
+                var interceptorRunner = interceptorRunnerService.get(runnerSource.getRunnerName());
+                interceptor.setEndpoint(interceptorRunner.getCompletionEndpoint());
+                interceptor.getFeatures().setConfigurationEndpoint(interceptorRunner.getConfigurationEndpoint());
+            }
+            if (exportFormat == ExportFormat.CORE || !componentTypes.contains(ExportConfigComponentType.INTERCEPTOR_RUNNER)) {
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/service/transfer/exporter/InterceptorExporter.java:77]: add tests for this changes

File: src/main/java/com/epam/aidial/cfg/domain/util/InterceptorEndpointResolver.java (hunk 1 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/domain/util/InterceptorEndpointResolver.java]: in next line configurationEndpoint set in features object. this changes will be lost if we don't hold ref on feature entity. let's write test for this case

Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/domain/util/InterceptorEndpointResolver.java]: There is a test that verifies this scenario: InterceptorFunctionalTest.shouldRefreshEndpointsForContainerSource

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/service/transfer/exporter/InterceptorExporter.java (hunk 3 above)
Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/service/transfer/exporter/InterceptorExporter.java:77]: Done, improved test coverage here

File: src/main/java/com/epam/aidial/cfg/domain/util/InterceptorEndpointResolver.java (hunk 1 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/domain/util/InterceptorEndpointResolver.java]: in this tests interceptor(entity) have already had object in features field.

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/domain/util/InterceptorEndpointResolver.java (hunk 1 above)
Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/domain/util/InterceptorEndpointResolver.java]: Oh now I see what you mean. Forgot to add '.setFeatures' at first

Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/domain/util/InterceptorEndpointResolver.java]: Added ContainerEndpointResolverTest

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by siarhei-fedziukovich — DISMISSED** [review]

**Comment by Pasichniuk** [comment]
NOTE: update DB migrations' version before merging & wait for FE readiness to support new fields

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by siarhei-fedziukovich — APPROVED** [review]

**Review by KirylKurnosenka — APPROVED** [review]
