### PR TITLE
fix: fix sync state comparison for model upstreams

### LINKED ISSUE #634: [Sync with core] “Out of sync” when Upstream Endpoints contain a mix of secured and unsecured entries (order mismatch).
### Name and Version

[FE]0.14.0-rc [BE]0.13.0-rc Core: [Default version]latest

### What steps will reproduce the bug?

1. Navigate to **Entities → Models**.
2. Create a new Model or open an existing one.
3. Add multiple Upstream Endpoints (Optional), ensuring some have keys and others do not.
4. Arrange the Upstream Endpoints so that those with keys are listed before those without keys.
5. Save the Model and synchronize with Core.
6. Observe the **Sync with core** status, which becomes **Out of sync**.
7. Open the **Sync with core** modal and compare the order of Upstream Endpoints between Admin and Core.

### What is the expected behavior?

- The **Sync with core** status should be **Synced** after saving and synchronizing, regardless of the order or presence of keys in Upstream Endpoints.
- The order of Upstream Endpoints should be consistent between Admin and Core.

### What do you see instead?

- The **Sync with core** status becomes **Out of sync** when Upstream Endpoints with keys precede those without keys in Admin.
- The order of Upstream Endpoints differs between Admin and Core, causing a synchronization mismatch.
- If all Upstream Endpoints have keys or none have keys, synchronization works as expected.

Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #634 

### Description of changes
Fix sync state comparison for model upstreams (ignore upstreams order)

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/test/java/com/epam/aidial/cfg/functional/tests/ModelFunctionalTest.java [hunk 1]
```diff
@@ -495,36 +496,54 @@ public void shouldResetAdapterToNullWhenChangingModelSourceFromAdapterToContaine
...
         modelFacade.createModel(modelDto);
 
         JsonNode config = coreConfig();
         CoreConfigReloadCache.Entry cacheEntry = new CoreConfigReloadCache.Entry(config, 1000);
         when(coreConfigReloadCache.get()).thenReturn(cacheEntry);
 
-        JsonNode modelState = config.get("models").get("model1");
+        JsonNode configModelState = config.get("models").get("model1");
+        JsonNode currentModelState = configModelState.deepCopy();
+        JsonNode upstreams = currentModelState.get("upstreams");
```
Comment (siarhei-fedziukovich) [inline src/test/java/com/epam/aidial/cfg/functional/tests/ModelFunctionalTest.java:522]: pls left comment. won't be obvious for viewer without context

Comment (KirylKurnosenka) [reply src/test/java/com/epam/aidial/cfg/functional/tests/ModelFunctionalTest.java:522]: added comment

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by siarhei-fedziukovich — APPROVED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>
