### PR TITLE
fix: provide auth status for toolset entity

### LINKED ISSUE #674: [Entities / Toolsets] OAuth authentication succeeds but authentication state is not updated
### Name and Version

0.14.0

### What steps will reproduce the bug?

Go to Entities → Toolsets.
Open an Entity Toolset.
Set Authentication method to OAuth.
Provide valid OAuth credentials / configuration.
Click Log in and complete OAuth flow successfully.

### What is the expected behavior?

After successful OAuth login:
Authentication state should be updated to “Logged in”
UI should reflect active authenticated state for the toolset

### What do you see instead?

OAuth login completes successfully.

Toolset remains in “Logged out” state.

Authentication status does not change.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #674 

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/client/mapper/OpenaiDeploymentsClientMapper.java [hunk 1]
```diff
@@ -0,0 +1,11 @@
+package com.epam.aidial.cfg.client.mapper;
+
+import com.epam.aidial.cfg.client.dto.ToolSetDataDto;
+import com.epam.aidial.cfg.model.ToolSetData;
+import org.mapstruct.Mapper;
+
+@Mapper(componentModel = "spring")
+public interface OpenaiDeploymentsClientMapper {
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/client/mapper/OpenaiDeploymentsClientMapper.java]: why `Openai` ?

File: src/main/java/com/epam/aidial/cfg/client/OpenaiDeploymentsClient.java [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+        url = "${core.client.url}",
+        configuration = {
+                AuthorizationCoreClientConfiguration.class,
+                RetryClientConfiguration.class,
+                FeignErrorDecoderConfiguration.class
+        })
+public interface OpenaiDeploymentsClient {
+
+    @GetMapping(value = "/openai/toolsets/{toolSetName}")
+    ToolSetDataDto getOpenaiToolSet(@PathVariable String toolSetName);
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/client/OpenaiDeploymentsClient.java]: pls remove `openai` prefix (here and in other places for toolsets). it was used in core route by mistake (to be in sync with other listing endpoints)

File: src/main/java/com/epam/aidial/cfg/service/OpenaiDeploymentsService.java [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+public class OpenaiDeploymentsService {
+
+    private final OpenaiDeploymentsClient openaiDeploymentsClient;
+    private final OpenaiDeploymentsClientMapper openaiDeploymentsClientMapper;
+
+    public Optional<ToolSetData> tryGetToolSet(String name) {
+        try {
+            return Optional.of(getToolSet(name));
+        } catch (Exception e) {
+            log.info("Failed to retrieve '{}' toolset from DIAL Core: {}", name, e.getMessage());
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/service/OpenaiDeploymentsService.java]: pls log origignal `e` (not only message) with any suitable level

Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/service/OpenaiDeploymentsService.java]: why `info`? not warn or debug?

File: src/main/java/com/epam/aidial/cfg/client/mapper/OpenaiDeploymentsClientMapper.java (hunk 1 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/client/mapper/OpenaiDeploymentsClientMapper.java]: refactored

File: src/main/java/com/epam/aidial/cfg/client/OpenaiDeploymentsClient.java (hunk 2 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/client/OpenaiDeploymentsClient.java]: refactored

File: src/main/java/com/epam/aidial/cfg/service/OpenaiDeploymentsService.java (hunk 3 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/service/OpenaiDeploymentsService.java]: changed to `e` instead of `e.getMessage()`

Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/service/OpenaiDeploymentsService.java]: changed to `warn`

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by siarhei-fedziukovich — DISMISSED** [review]

**Comment by KirylKurnosenka** [comment]
Considering approval as a permission to resolve comments on my own

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by siarhei-fedziukovich — APPROVED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>
