### PR TITLE
fix: unify role limits import for admin and core formats

### LINKED ISSUE #166: Import Admin fails for model with role limits
### Name and Version

0.6.0

### What steps will reproduce the bug?

1. Go to admin ->Models
2. Create  Model with Role limits
3. Export in admin format  (choose the same model with same role with limits)
4. Import in Admin format  this model (just exported model, no edits)

### What is the expected behavior?

Importing own export is successful; model , role and limits are restored without errors

### What do you see instead?

Import returns Bad Request message

### Additional information

Image

### LINKED ISSUE #170: Role share is empty after importing a model with role via config
### Name and Version

0.6.0

### What steps will reproduce the bug?

1. Go to DIAL Admin
2. Import Config with Model +Role + share (reference to model)
3.Go to Roles
3.Open Roles [that role] and JSON Editor toggle
4. Observe share field in JSON file 

### What is the expected behavior?

Role's JSON contains the share block with the imported values

### What do you see instead?

Role's share is empty/missing in JSON Editor

Image

### Additional information

_No response_

### LINKED ISSUE #171: Importing JSON with another role causes error and does not update the model-role link
### Name and Version

0.6.0

### What steps will reproduce the bug?

Model has been created
Prepared a JSON file with the same model but with different role.

1.Go to DIAL Admin
2. Got to the import core config and import the JSON file
3. Observe the message

### What is the expected behavior?

The previous role should no longer have the model in its Role list
The model should now have the new role specified in the imported JSON
The new role should contain a link to the model

### What do you see instead?

The import fails with an error
The role model link isn't updated

### Additional information

Image

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #166
- fixes #170
- fixes #171

### Description of changes

Unified role limits import for admin and core format. Since role limits are defined under roles (not models, applications, etc) in Admin and Core config, they are imported with roles.

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by siarhei-fedziukovich — DISMISSED** [review]

File: src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+            return null;
+        }
+        return deployment.getRoleLimits().stream()
+                .filter(RoleLimit::isEnabled)
+                .map(this::mapUserRole)
+                .collect(Collectors.toSet());
+    }
+
+    private String mapUserRole(RoleLimit limit) {
+        return limit != null ? limit.getRole() : null;
```
Comment (Pasichniuk) [inline src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java]: If limit is null, null will be added to Set. Let's filter limits before mapping.

File: src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+    }
+
+    @Mapping(target = "name", source = "name")
```
Comment (Pasichniuk) [inline src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java]: Is this @Mapping needed?

File: src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+    @Mapping(target = "defaultRoleLimit", expression = "java(mapToDefaultRoleLimit())")
```
Comment (Pasichniuk) [inline src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java]: I haven't seen this approach with expression anywhere in our code, maybe it's better to use a named method?

File: src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java (hunk 1 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java]: Actually that code was extracted from RoleLimitMapper
image
But you are right, we shouldn't put null into set, and actually, incoming limits can not be null, so will adjust mapping instead of filtering

File: src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java (hunk 2 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java]: Actually no, removed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java (hunk 3 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java]: named method requires source, whereas there is no source for defaultRoleLimit mapping.
decided to do mapping manually

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+                .collect(Collectors.toSet());
+    }
+
+    default Deployment toDeployment(RoleBasedEntity roleBasedEntity) {
+        if (roleBasedEntity == null) {
+            return null;
+        }
+
+        Deployment deployment = new Deployment(roleBasedEntity.getName());
+        deployment.setIsPublic(CollectionUtils.isEmpty(roleBasedEntity.getUserRoles()));
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java]: empty collection ( [] ) doesn't mean public

**Review by siarhei-fedziukovich — APPROVED** [review]

File: src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java (hunk 4 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/domain/mapper/DeploymentCoreMapper.java]: changed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by Pasichniuk — APPROVED** [review]
