### PR TITLE
fix: adjust export configuration

### LINKED ISSUE #195: Telemetry doesn't work BE configured with CONFIG_EXPORT_ENABLED=false
### Name and Version

0.5.0

### What steps will reproduce the bug?

1. set CONFIG_EXPORT_ENABLED=false for BE
2. run BE
3. try query telemetry/metrics

### What is the expected behavior?

no error

### What do you see instead?

```
[32m2025-08-27T02:39:33,226[m  [33mWARN [m trace_id:  span_id= [[1;34mmain[m] [1;33mo.s.c.a.AnnotationConfigApplicationContext[m: Exception thrown from ApplicationListener handling ContextClosedEvent
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'meterRegistryCloser': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
"	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:303)"
"	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337)"
"	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)"
"	at org.springframework.context.event.AbstractApplicationEventMulticaster.retrieveApplicationListeners(AbstractApplicationEventMulticaster.java:267)"
"	at org.springframework.context.event.AbstractApplicationEventMulticaster.getApplicationListeners(AbstractApplicationEventMulticaster.java:223)"
"	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145)"
"	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:454)"
"	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:460)"
"	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:387)"
"	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1163)"
"	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1126)"
"	at org.springframework.cloud.context.named.NamedContextFactory.destroy(NamedContextFactory.java:114)"
"	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:211)"
"	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:798)"
"	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:748)"
"	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1474)"
"	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:707)"
"	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1467)"
"	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1219)"
"	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:640)"
"	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)"
"	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)"
"	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439)"
"	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318)"
"	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1361)"
"	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1350)"
"	at com.epam.aidial.cfg.Application.main(Application.java:14)"
"	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
"	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)"
"	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)"
"	at java.base/java.lang.reflect.Method.invoke(Unknown Source)"
"	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:102)"
"	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64)"
"	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:40)"
```

### Additional information

related to https://github.com/epam/ai-dial-admin-backend/issues/132

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #195

### Description of changes
Adjusted export configuration
- `config.export.enabled` property affects only scheduled export
- introduced `config.reload.enabled` property which defines whether writing config to destination storage and calling the `/reload_config` endpoint on core is enabled or not

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/service/export/ConfigExportScheduler.java [hunk 1]
```diff
@@ -21,31 +17,23 @@
...
-    private final ConfigExportErrorHandler errorHandler;
     private final Optional<CoreConfigAutoImportOnBootstrapLock> coreConfigAutoImportLock;
-
-    @Value("${config.export.createResources}")
-    private boolean createResources;
+    private final ConfigExportFacade configExportFacade;
+    private final ConfigExportErrorHandler errorHandler;
 
     @Scheduled(fixedDelayString = "${config.export.syncPeriod}")
-    @Synchronized
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/service/export/ConfigExportScheduler.java:37]: Removed since it's not longer called concurrently

File: src/main/java/com/epam/aidial/cfg/service/export/ConfigExportFacade.java [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+                              ConfigExportService configExportService,
+                              List<CoreConfigNormalizer> normalizers,
+                              @Value("${config.export.createResources}") boolean createResources) {
+        this.configService = configService;
+        this.configExportService = configExportService;
+        this.normalizers = normalizers;
+        this.createResources = createResources;
+    }
+
+    public void exportCurrentConfig() {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/service/export/ConfigExportFacade.java:33]: Can be called either during scheduled export or manual config reload, but concurrency is handled by `configTransferLock` inside `configExportService`

**Review by siarhei-fedziukovich — APPROVED** [review]
