### PR TITLE
fix!: validate entity id is not empty and doesn't have illegal characters during creation

### LINKED ISSUE #63: Error 400 when opening key with invalid name - no backend constraint
### Name and Version

0.5.0

### What steps will reproduce the bug?

1. Go to Admin panel
2. Open Access management -> Keys
3. Create Key with invalid name
4. Observe backend response

### What is the expected behavior?

The system should prevent creation or use of keys with invalid names.

### What do you see instead?

Return 400 Bad Request with error Request error, URL becomes wrong due to invalid name

### Additional information

_No response_

### LINKED ISSUE #83: Model can be created/deleted with invalid characters in the name
### Name and Version

0.5.0

### What steps will reproduce the bug?

1. Go to the admin panel
2. Open the Models section
3. Click Create Model
4. Enter a name that includes special characters (~, #, /, &  etc.)
5. Save the model
6. Try deleting the model

### What is the expected behavior?

The system should prevent creating a model if the name contains invalid or special characters.

### What do you see instead?

The model is successfully created with special characters in the name.

Image

### Additional information

_No response_

### LINKED ISSUE #90: [Models] Cannot open model when deployment id contains '/'
### Name and Version

ai-dial-admin 0.5.0-rc

### What steps will reproduce the bug?

1. Open Models
2. Click "Create"
3. Fill in all required fields. For deployment, use a string that contains a forward slash (`/`), for example, `meta/llama-3.2-1b`
4. Click on the newly created model

### What is the expected behavior?

The model details page opens

### What do you see instead?

The model details page does not open

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #63
- fixes #83
- fixes #90

### Description of changes
Added validation that entity id (which is usually `name`) is not empty and doesn't have illegal characters during creation

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by siarhei-fedziukovich** [comment]
mark PR as breaking change

**Review by siarhei-fedziukovich — DISMISSED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by KirylKurnosenka** [comment]
> mark PR as breaking change

**Comment by KirylKurnosenka** [comment]
> mark PR as breaking change

>marked

File: src/main/java/com/epam/aidial/cfg/domain/validator/IdFieldValidator.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+
+@Component
+public class IdFieldValidator {
+
+    private static final Set<Character> NAME_ILLEGAL_CHARACTERS = Set.of('%', ';', '/', '\\');
+
+    public void validateName(String domainObjectType, String name) {
+        validateId(domainObjectType, name, "name");
+
+        for (var character : name.toCharArray()) {
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/domain/validator/IdFieldValidator.java]: NxM loop looks ugly for me. I'd use regex here

File: src/test/java/com/epam/aidial/cfg/domain/validator/AddonValidatorTest.java [hunk 2]
```diff
@@ -75,4 +78,22 @@ void validateAddonCreation_shouldThrowExceptionForInvalidName(String name) {
...
+
+        Addon addon = new Addon();
+        addon.setDeployment(deployment);
+
+        doThrow(IllegalArgumentException.class).when(deploymentValidator)
+                .validateCreation("Addon", deploymentName);
+
+        // when/then
+        Assertions.assertThatThrownBy(() -> addonValidator.validateAddonCreation(addon))
+                .isInstanceOf(IllegalArgumentException.class);
```
Comment (siarhei-fedziukovich) [inline src/test/java/com/epam/aidial/cfg/domain/validator/AddonValidatorTest.java:96]: i guess reason is empty name but not sure. reason is not obvious (add comment/rename test method/add assertion)./

**Review by siarhei-fedziukovich — DISMISSED** [review]

File: src/main/java/com/epam/aidial/cfg/domain/validator/IdFieldValidator.java (hunk 1 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/domain/validator/IdFieldValidator.java]: Changed to regex

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by siarhei-fedziukovich — APPROVED** [review]
