### PR TITLE
fix: rollback should not lose 'source' & rollback should be possible for 'authSettings'

### LINKED ISSUE #292: Source type becomes External Endpoint from MCP Container after any changes in Toolset and Resource rollback in Activities and any changes in Authentication can't be Rollback
### Name and Version

BE: 0.9.0-rc

### What steps will reproduce the bug?

1. Open some Toolset, change Source Type to MCP Container and Save it
2. Change description and Save it
3. Go to Activities, make roolback for the description and check Source type

1. 1. Open some Toolset, make any changes in Authentication and Save it
2. Go to Activities and try to make rollback for the previous step

### What is the expected behavior?

Any changes in Toolset can be Rollback correctly

### What do you see instead?

Source type becomes External Endpoint from MCP Container after any changes in Toolset and Resource rollback in Activities and any changes in Authentication can't be Rollback

Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Pasichniuk**
### Applicable issues

- fixes #292 

### Description of changes

- Added ability to rollback 'defaultRoleLimit' & 'defaultRoleShareResourceLimit'
- Added ability to rollback 'authSettings' (ToolSet)
- Fixed rollback for 'source' (ToolSet/Model/Interceptor)

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/utils/AuthSettingsComparator.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+import java.util.List;
+import java.util.Objects;
+
+/**
+ * Utility class for comparing auth settings between domain and entity models.
+ */
+@UtilityClass
+public class AuthSettingsComparator {
+
+    public static boolean isChanged(ResourceAuthSettings domainAuthSettings, ResourceAuthSettingsEntity entityAuthSettings) {
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/utils/AuthSettingsComparator.java]: why do you do it with util class? it's looks like equals method inside ResourceAuthSettings isn't it?

File: src/main/java/com/epam/aidial/cfg/dao/mapper/ToolSetEntityMapper.java [hunk 2]
```diff
@@ -55,8 +56,16 @@ public ToolSetEntity toEntity(ToolSet domain, ToolSetEntity entity) {
             toolSetContainer = toolSetContainerEntityMapper.toEntity(containerSource);
         }
 
+        var domainAuthSettings = domain.getDeployment() != null ? domain.getDeployment().getAuthSettings() : null;
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/dao/mapper/ToolSetEntityMapper.java]: Is there a chance deployment could be null for either domain or entity?

File: src/main/java/com/epam/aidial/cfg/dao/mapper/ToolSetEntityMapper.java [hunk 3]
```diff
@@ -55,8 +56,16 @@ public ToolSetEntity toEntity(ToolSet domain, ToolSetEntity entity) {
...
+        var entityAuthSettings = entity.getDeployment() != null ? entity.getDeployment().getAuthSettings() : null;
+
         ToolSetEntity updatedEntity = update(domain, entity);
 
+        // Auth Settings update is not reflected in ToolSet's audit table, so provoking a dirty entity by manually setting 'updatedAt'
+        if (AuthSettingsComparator.isChanged(domainAuthSettings, entityAuthSettings)) {
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/dao/mapper/ToolSetEntityMapper.java]: it's a new pattern. how does it work for another base (deploymentEntity) properties?

Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/dao/mapper/ToolSetEntityMapper.java]: How it differs from other deployment entity fields? May be it makes sense to look into `ConfigRevisionListener` instead of such hack?

File: src/main/java/com/epam/aidial/cfg/dao/model/ContainerEntity.java [hunk 4]
```diff
@@ -1,10 +1,15 @@
 package com.epam.aidial.cfg.dao.model;
 
+import jakarta.persistence.EntityListeners;
 import jakarta.persistence.MappedSuperclass;
 import lombok.Data;
+import org.hibernate.envers.Audited;
+import org.springframework.data.jpa.domain.support.AuditingEntityListener;
 
 @Data
+@Audited
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/dao/model/ContainerEntity.java:8]: Why is that needed? Envers doesn't automatically handle embedded fields?

Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/dao/model/ContainerEntity.java:8]: It doesn't, that's the reason why we lose 'source' on rollback

File: src/main/java/com/epam/aidial/cfg/dao/mapper/ToolSetEntityMapper.java (hunk 3 above)
Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/dao/mapper/ToolSetEntityMapper.java]: Auth settings field is embedded. Actually, same problem exists for 'defaultRoleLimit' & 'defaultRoleShareResourceLimit' - but they are set on a separate UI page (not on 'Properties' like 'authSettings'), that's why it wasn't noticed I guess

Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/dao/mapper/ToolSetEntityMapper.java]: Auditing works fine for all deploymentEntity's properties except embedded ones like 'authSettings', 'defaultRoleLimit' & 'defaultRoleShareResourceLimit', as I mentioned in the next comment

File: src/main/java/com/epam/aidial/cfg/dao/mapper/ToolSetEntityMapper.java (hunk 2 above)
Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/dao/mapper/ToolSetEntityMapper.java]: In real world scenario probably not, but it frequently happens in tests

File: src/main/java/com/epam/aidial/cfg/utils/AuthSettingsComparator.java (hunk 1 above)
Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/utils/AuthSettingsComparator.java]: This util class compares domain object and entity object. Maybe it makes sense to first map entity to domain and then use equals, but these operations are redundant, in my opinion

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/dao/mapper/ToolSetEntityMapper.java (hunk 3 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/dao/mapper/ToolSetEntityMapper.java]: let's fix other embedded entities if there are issues too ( defaultRoleLimit and defaultRoleShareResourceLimit)

File: src/main/java/com/epam/aidial/cfg/utils/AuthSettingsComparator.java (hunk 1 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/utils/AuthSettingsComparator.java]: map and equals reduce complexicity. less code less issues

Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/utils/AuthSettingsComparator.java]: refactored

File: src/main/java/com/epam/aidial/cfg/dao/mapper/ToolSetEntityMapper.java (hunk 3 above)
Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/dao/mapper/ToolSetEntityMapper.java]: fixed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by siarhei-fedziukovich — DISMISSED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/dao/model/ContainerEntity.java [hunk 5]
```diff
@@ -1,10 +1,15 @@
...
 @MappedSuperclass
+@EntityListeners(AuditingEntityListener.class)
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/dao/model/ContainerEntity.java]: How does that help considering that ContainerEntity and all subclasses don't have audit field?

File: src/main/java/com/epam/aidial/cfg/dao/model/ContainerEntity.java (hunk 4 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/dao/model/ContainerEntity.java:8]: May be that is because of @MapperSuperclass?

I prepared such simple test

Image
where model features is embedded class without `@Audited` annotation
and after updated I have 2 rows in model_entity_aud, where second row has new value in `rate_endpoint` field

Image

Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/dao/model/ContainerEntity.java:8]: Looks like @MappedSuperclass is the reason, but we can't remove it. Without 'Audited' source is lost on rollback

File: src/main/java/com/epam/aidial/cfg/dao/model/ContainerEntity.java (hunk 5 above)
Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/dao/model/ContainerEntity.java]: Leftover, removed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by KirylKurnosenka — APPROVED** [review]
