### PR TITLE
fix: Files and subfolders are not include when exporting a folder

### LINKED ISSUE #728: [Assets][Files] Files and subfolders are not include when exporting a folder
### Name and Version

[FE]0.15.0-rc [BE]0.15.0-rc

### What steps will reproduce the bug?

BE support is required. Related to FE bug:   https://github.com/epam/ai-dial-admin-frontend/issues/2427 

Go to Assets → Files.
Select a folder that contains:
• Files directly inside it
• One or more subfolders (with files inside them).
Click Export.
Open the exported archive.

### What is the expected behavior?

The export should include: All files inside the selected folder; All nested subfolders; All files inside subfolders.

### What do you see instead?

• Only the selected folder is exported.
• Files inside the folder are missing.
• Subfolders and their files are not included in the export.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Katerina-Charakhovich**
### Applicable issues

- fixes #728

### Checklist

- [ ] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by siarhei-fedziukovich — DISMISSED** [review]

File: src/main/java/com/epam/aidial/cfg/service/FileService.java [hunk 1]
```diff
@@ -274,9 +278,9 @@ public ResourceType getResourceType() {
         return ResourceType.FILE;
     }
 
-    public StreamingResponseBody export(List<String> paths) {
-        var distinctPaths = paths.stream()
-                .distinct()
+    public StreamingResponseBody export(ExportDto exportDto) {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/service/FileService.java]: Is ExportDto instead of List<String> paths needed? If so, let's map dto to model as it's done for other dtos in order to not create dependency on dto package in service

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/service/FileService.java [hunk 2]
```diff
@@ -317,4 +321,44 @@ public boolean fileExists(String path) {
...
+    private Set<String> collectFilePathsByPath(String path) {
+        if (!PathUtils.isFolderPath(path)) {
+            return path != null && !path.isEmpty() ? Set.of(path) : Collections.emptySet();
+        }
+        try {
+            var request = ResourceMetadataRequest.builder()
+                    .path(path)
+                    .recursive(true)
+                    .build();
+            FileNodeInfo node = getAll(request);
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/service/FileService.java:342]: does pagination includes in getAll?

File: src/main/java/com/epam/aidial/cfg/service/FileService.java (hunk 1 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/service/FileService.java]: updated

File: src/main/java/com/epam/aidial/cfg/service/FileService.java (hunk 2 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/service/FileService.java:342]: No, doesn't

**Comment by KirylKurnosenka** [comment]
Shouldn't the same fix be done for other resources?

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by KirylKurnosenka — APPROVED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>
