### PR TITLE
fix: fix MCP introspection. mcpEndpoint should be passed to builder b…

### LINKED ISSUE #338: MCP tools instrospection doesn't work if MCP exposes non standart relative path
### Name and Version

0.9.0

### What steps will reproduce the bug?

register MCP server with non standard path. open tools tab in toolset view.

### What is the expected behavior?

list of discovered tools are displayed

### What do you see instead?

tools discovery doesn't detect any tools

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by siarhei-fedziukovich**
### Applicable issues

- fixes #338 

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/client/mcp/McpClientFactory.java [hunk 1]
```diff
@@ -7,18 +7,40 @@
...
 @Component
 @LogExecution
 @RequiredArgsConstructor
 public class McpClientFactory {
 
-    public McpSyncClient create(String baseUrl, Transport transport) {
+    @SneakyThrows
+    public McpSyncClient create(String mcpEndpoint, Transport transport) {
+        var uri = new URI(mcpEndpoint);
+        var baseUrl = uri.getScheme() + "://" + uri.getAuthority();
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/client/mcp/McpClientFactory.java:24]: I'm wondering why there is no built-in method to get baseUrl without manual concatenion of scheme, authority and their separator

As an alternative
```
var baseUrl = new URI(uri.getScheme(), uri.getAuthority(), null, null, null).toString();
```
Resolve comment if you like to go ahead with current approach

**Review by KirylKurnosenka — APPROVED** [review]

**Review by Pasichniuk — APPROVED** [review]
