### PR TITLE
fix: Bad-Request-error-occurs-while-trying-to-move-app-to-the-folder-with-spaces-in-the-name

### LINKED ISSUE #847: [Approvals-Application Publications] Bad Request error occurs while trying to move app to the folder with spaces in the name.
### EPAM AI DIAL Admin version

Admin: [FE]0.16.0-rc [BE]0.16.0-rc

### How to reproduce

DEV environment.

**Preconditions:**
1. Create a new application or edit an existed one in the Chat.
2. Publish it.

**Steps:**
1. Navigate to Approvals -> Application Publications
2. Open application publication.
3. Move it to the folder that has spaces in the name.
4. Click 'Save'.

### Actual result

En error occurs. The application can't be moved to the folder with spaces in the name.

Image

Image

### Expected result

The application can be moved to the folder with spaces in the name. The changes have been saved successfully.
A new path is displayed in the Folder Storage field.

### Additional information

_No response_

### Confidential information

- [x] I confirm that do not share any confidential information

### PR DESCRIPTION
**Pull request by Katerina-Charakhovich**
### Applicable issues

- fixes #847 

### Checklist

- [ ] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/client/mapper/PublicationClientMapper.java [hunk 1]
```diff
@@ -81,7 +81,7 @@ default PromptPublication toPromptPublication(PublicationDto dto, List<PromptPub
     }
 
     @Mapping(target = "requestName", source = "dto.name")
-    @Mapping(target = "folderId", source = "dto.targetFolder")
+    @Mapping(target = "folderId", source = "dto.targetFolder", qualifiedByName = "decodePath")
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/client/mapper/PublicationClientMapper.java:84]: Could you please clarify why decoding is needed when mapping from client dto to model?

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/client/mapper/PublicationClientMapper.java (hunk 1 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/client/mapper/PublicationClientMapper.java:84]: To normalize the path for the front-end .
image

**Review by KirylKurnosenka — APPROVED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None
