### PR TITLE
fix: use system user for background tasks

### LINKED ISSUE #659: Admin changes the config and displays `initiated` when the settings (url/mcp_transport) are changed in deployment of the model
### EPAM AI DIAL Admin version

[FE]0.14.0-rc [BE]0.14.0-rc

### How to reproduce

1. Create Model Serving, run it, and create the model
2. Change url/mcp_transport

### Actual result

Admin changes the config and displays `initiated` when the settings (url/mcp_transport) are changed in deployment of the model

Image

### Expected result

Add something like: system_user plus add:
- Add validation not to allow work for a real user with such a name;
- Add documentation about such a system_user

### Additional information

_No response_

### Confidential information

- [x] I confirm that do not share any confidential information

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #659 

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by Katerina-Charakhovich — DISMISSED** [review]

File: src/main/java/com/epam/aidial/cfg/security/SystemSecurityContextExecutor.java [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+
+        try {
+            setSystemContext();
+            task.run();
+        } finally {
+            setPreviousContextOrClear(previous);
+        }
+    }
+
+    public <T> T runAsSystemUser(Callable<T> task) throws Exception {
```
Comment (Katerina-Charakhovich) [inline src/main/java/com/epam/aidial/cfg/security/SystemSecurityContextExecutor.java]: Looks like this method is not used anywhere.

Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/security/SystemSecurityContextExecutor.java]: Yes, that's true. Added for further development convenience: just use existing method instead of writing it on your own. I can remove it if you have concerns

Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/security/SystemSecurityContextExecutor.java]: Changed approach

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/security/aspect/RunAsInternalUserAspect.java [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+import org.springframework.security.core.context.SecurityContextHolder;
+import org.springframework.stereotype.Component;
+
+import java.util.Arrays;
+import java.util.List;
+
+@Aspect
+@Component
+@LogExecution
+public class RunAsInternalUserAspect {
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/security/aspect/RunAsInternalUserAspect.java:20]: opt: add unittest

File: src/main/java/com/epam/aidial/cfg/web/security/JwtAuthenticationConverter.java [hunk 3]
```diff
@@ -41,6 +42,12 @@ public AbstractAuthenticationToken convert(@NotNull Jwt jwt) {
         var userRoles = userRolesResolver.resolve(authorities);
         var principalClaimValue = jwt.getClaimAsString(principalClaim);
 
+        if (InternalSecurityAuthenticationToken.isReservedInternalPrincipal(principalClaimValue)) {
+            log.warn("{} principal is forbidden - issuer: {}, authorities: {}, user roles: {}",
+                    principalClaimValue, issuer, authorities, userRoles);
+            return new JwtAuthenticationToken(jwt);
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/web/security/JwtAuthenticationConverter.java]: non consistent with src/main/java/com/epam/aidial/cfg/web/security/DefaultOpaqueTokenIntrospector.java. here returns empty token but in Opaque throws ex. does it intentionally?

File: src/main/java/com/epam/aidial/cfg/web/security/DefaultOpaqueTokenIntrospector.java [hunk 4]
```diff
@@ -43,8 +44,16 @@ public OAuth2AuthenticatedPrincipal introspect(String token) {
         Map<String, Object> newAttributes = new HashMap<>(attributes);
         newAttributes.put(OpaqueTokenProviderConfig.IDP_CLAIM, config.getName());
 
+        var principalClaimValue = (String) attributes.get(principalClaim);
+
+        if (InternalSecurityAuthenticationToken.isReservedInternalPrincipal(principalClaimValue)) {
+            String message = "%s principal is forbidden".formatted(principalClaimValue);
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/web/security/DefaultOpaqueTokenIntrospector.java]: unittest?

**Review by siarhei-fedziukovich — DISMISSED** [review]

File: src/main/java/com/epam/aidial/cfg/security/aspect/RunAsInternalUserAspect.java (hunk 2 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/security/aspect/RunAsInternalUserAspect.java:20]: added tests

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/web/security/JwtAuthenticationConverter.java (hunk 3 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/web/security/JwtAuthenticationConverter.java]: Refactored JwtAuthenticationConverter.java + moved the check from DefaultOpaqueTokenIntrospector.java to OpaqueAuthenticationConverter.java so now they look quite similar

File: src/main/java/com/epam/aidial/cfg/web/security/DefaultOpaqueTokenIntrospector.java (hunk 4 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/web/security/DefaultOpaqueTokenIntrospector.java]: Added integration tests

Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/web/security/DefaultOpaqueTokenIntrospector.java]: Added unit tests as well

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by Katerina-Charakhovich — APPROVED** [review]

**Review by siarhei-fedziukovich — APPROVED** [review]

**Comment by KirylKurnosenka** [comment]
Considering approvals as a permission to resolve comments on my own

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>
