### PR TITLE
fix: use UUID as key name when importing core keys, use key value as json object key when exporting core keys, exclude keys from core export/preview when addSecrets option is false

### LINKED ISSUE #126: Imported API keys from core config retain key values as names instead of generating UUIDs
### Name and Version

0.0.5

### What steps will reproduce the bug?

1. Prepare a core configuration file containing API keys
2. Navigate to the admin panel import functionality
3. Import the core configuration file
4. After successful import, navigate to the keys management section
5. Observe the "Key Name" field for the newly imported keys

### What is the expected behavior?

When importing API keys from a core configuration file, the system should automatically generate unique UUID values for the "Key Name" field of each imported key. This ensures:

* Unique identifiers that don't expose sensitive information
* Proper separation between the key's identifier (name) and its actual value

### What do you see instead?

The imported keys have their "Key Name" field populated with the same value as the actual API key value itself. This means:

* The key value is duplicated in both the "Key Name" and "Key Value" fields
* Potential security concern as key values may be exposed in places where only names should be displayed

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #126

### Description of changes

- Used UUID instead of key value (which is sensitive) for key name when importing Core keys
- Used key value instead of key name as json object key when exporting Core keys
- Excluded keys from Core export/preview when `addSecrets` option is `false`

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/test/java/com/epam/aidial/cfg/functional/tests/ConfigTransferFunctionalTest.java [hunk 1]
```diff
@@ -1421,6 +1551,14 @@ private String getAppRunnerDtoWithRequiredFields(List<String> requiredFields) {
                 }""".formatted(requiredFieldsString);
     }
 
+    private String findKeyNameByProject(String project) {
+        return keyFacade.getAllKeys().stream()
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/functional/tests/ConfigTransferFunctionalTest.java:1555]: `keyFacade.getAllKeys()` return key dtos where `key` field is `null`, therefore there is no possibility to find key by its value.
and I decided to make `project` field unique for keys in tests in order to be able to find key by project and then get its name which is generated random UUID

File: src/test/java/com/epam/aidial/cfg/functional/tests/ConfigTransferFunctionalTest.java [hunk 2]
```diff
@@ -815,10 +821,69 @@ void testExport_CoreFormatKeyWithAllDependencies_SelectedItemsExportRequest(bool
...
+                testKey1Name,
+                ExportConfigComponentType.KEY,
+                Set.of(ExportConfigComponentType.APPLICATION,
+                        ExportConfigComponentType.MODEL,
+                        ExportConfigComponentType.ROUTE,
+                        ExportConfigComponentType.ROLE,
+                        ExportConfigComponentType.INTERCEPTOR,
+                        ExportConfigComponentType.APPLICATION_TYPE_SCHEMA)
+        )));
+        // when
```
Comment (Pasichniuk) [inline src/test/java/com/epam/aidial/cfg/functional/tests/ConfigTransferFunctionalTest.java:877]: this '// when' duplicate can be removed

File: src/test/java/com/epam/aidial/cfg/service/transfer/importer/KeyImporterTest.java [hunk 3]
```diff
@@ -1,60 +0,0 @@
...
-import org.junit.jupiter.params.provider.Arguments;
-import org.junit.jupiter.params.provider.MethodSource;
-import org.mapstruct.factory.Mappers;
-
-import java.util.List;
-import java.util.stream.Stream;
-
-import static org.mockito.Mockito.mock;
-
-class KeyImporterTest {
```
Comment (Pasichniuk) [inline src/test/java/com/epam/aidial/cfg/service/transfer/importer/KeyImporterTest.java:19]: why this test is removed?

Comment (KirylKurnosenka) [reply src/test/java/com/epam/aidial/cfg/service/transfer/importer/KeyImporterTest.java:19]: Because the only one method under test was removed from original class

File: src/test/java/com/epam/aidial/cfg/functional/tests/ConfigTransferFunctionalTest.java (hunk 2 above)
Comment (KirylKurnosenka) [reply src/test/java/com/epam/aidial/cfg/functional/tests/ConfigTransferFunctionalTest.java:877]: Removed above

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by Pasichniuk — APPROVED** [review]
