### PR TITLE
fix: improve performance of influx2 engine

### LINKED ISSUE #875: [Audit/Dashboard/Usage Log] Fails to load with 504 gateway timeout and unexpected response Error.
### EPAM AI DIAL Admin version

[FE]0.16.0-rc [BE]0.16.0-rc Core: [Default version]lates

### How to reproduce

1. Navigate to **Audit → Dashboard** in the application.  
2. Monitor the loading spinner or activity indicator as the system attempts to fetch data.  
3. Open **Developer Tools (Dev Tools)** in your browser (e.g., pressing `F12` or `Ctrl+Shift+I` on Chrome).  
4. Observe errors in the **Network** or **Console** tabs:  
   - **Failed to load resource: the server responded with a status of 504 ().**  
   - **Error executing request: Error: An unexpected response was received from the server.**  

### Actual result

- The dashboard fails to load data, leaving the page blank or stuck with a persistent spinner.  
- The browser dev tools display the following errors:  
  - **Failed to load resource: the server responded with a status of 504 ().**  
  - **Error executing request: Error: An unexpected response was received from the server.**

Image

### Expected result

- The dashboard should fetch and display data within a reasonable timeframe.  
- No timeout or server-side errors should occur during data fetching.  
- In cases of server-side issues, the system should handle errors gracefully and display a user-friendly message (e.g., "Data temporarily unavailable. Please try again later.")  

### Additional information

_No response_

### Confidential information

- [x] I confirm that do not share any confidential information

### PR DESCRIPTION
**Pull request by oleksii-donets**
### Applicable issues

- fixes #875

#### Problem

Dashboard aggregation queries on the `analytics` bucket time out at the API gateway (504). Every Flux aggregation runs `schema.fieldsAsCols()` immediately after the measurement filter, which pivots every series into a full-column row layout before any filtering — an O(rows × fields) cost on a bucket with ~20 fields and 100k+ rows in the dashboard time range.

#### Changes

Two complementary optimizations in `FluxQueryBuilder`:

1. **Field-filter fast path** (`buildFieldFilterAggregation`) — when a query's group-by and WHERE clauses reference only tags, the pivot is skipped entirely. The aggregation pushes `filter(_field == "…")` to the storage engine and aggregates on `_value` directly. This is the single largest win for dashboard queries, which are mostly `count()`, `sum(tokens)`, `group by deployment/project_id` — all tag-only.
2. **Pivot filter split** (`splitFilterForPivot`) — when a query does reference fields (so the pivot is required), tag-only predicates in the WHERE clause are applied *before* `schema.fieldsAsCols()` so they can still be pushed to the storage engine, while field predicates stay after the pivot.

Gating (`canUseFieldFilterFastPath`) is conservative: any field reference in group-by or WHERE, or a `NOT` in the WHERE, falls back to the legacy pivot path. `sum(CASE WHEN field = 'x' THEN 1 END)` stays on the fast path by rewriting the case-when condition against `_value`.

Accompanying refactor: four near-identical aggregation builders collapsed into `buildFieldFilterAggregation` / `buildPivotAggregation`, plus shared helpers (`combineAggregations`, `createNullFillPart`, `resolveEffectiveFunction`, `addCaseWhenFilter`).

#### Tests

- All existing `FluxQueryBuilderTest` / `FluxQueryIntegrationTest` golden queries updated to reflect the new Flux output — the diff shows exactly how the generated queries change.
- New `perfTest` Gradle task (tagged `performance`, excluded from default `test`) runs the seven dashboard queries against Testcontainers-backed InfluxDB 2 and InfluxDB 3 instances seeded with 100k deterministic records. Use it to compare engines and track regressions:

  ```
  ./gradlew :perfTest
  ```

  Bump `WARMUP_RUNS` / `MEASURED_RUNS` in `AbstractInfluxPerformanceTest` for a real benchmark (single cold run by default; percentiles in the log output are only meaningful when `MEASURED_RUNS > 1`).

#### Before/after

_To be filled in from `perfTest` output against the dashboard query set._

### Checklist

- [X] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java [hunk 1]
```diff
@@ -542,127 +494,340 @@ private FluxQueryPart buildSimpleAggregationQuery(
...
+        var tempJoinTables = IntStream.range(0, aggregations.size() - 1)
+                .mapToObj(i -> getNewTemporaryName(TEMPORAL_TABLE_NAME)).toList();
+
+        for (int i = 0; i < aggregations.size(); i++) {
+            var agg = aggregations.get(i);
+            combiner.add(tempTables.get(i) + " = " + agg.getQuery(), agg.getImports(), agg.getPreamble());
+        }
+
+        combiner.add("%s = join(tables: {t1: %s, t2: %s}, on: %s)".formatted(
+                tempJoinTables.get(0), tempTables.get(0), tempTables.get(1), joinKeysCombined));
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java:566]: Can `aggregations` be empty list? If so, these `.get(0)` will throw exception

File: src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java [hunk 2]
```diff
@@ -542,127 +494,340 @@ private FluxQueryPart buildSimpleAggregationQuery(
...
+        return FluxConditionPartBuilder.createFilterPart(FIELD_COLUMN, fieldName);
+    }
+
+    private static boolean isCaseWhenSum(FunctionImpl function, List<Expression> args) {
+        return "sum".equals(function.getName())
+                && args.size() == 1 && args.get(0) instanceof CaseWhenExpression;
+    }
+
+    private boolean isCaseWhenAgainstFirstField(InfluxTableDeclaration tableDeclaration, List<Expression> args) {
+        var caseWhen = (CaseWhenExpression) args.get(0);
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java:766]: Can `args` be empty list?

File: src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java [hunk 3]
```diff
@@ -542,127 +494,340 @@ private FluxQueryPart buildSimpleAggregationQuery(
...
+     * Adds a case-when filter to the combiner if the aggregation is {@code sum(caseWhen)}.
+     *
+     * @param targetColumn the column to compare against, or null to use the original column name
+     */
+    private void addCaseWhenFilter(InfluxQueryPartCombiner combiner, FunctionImpl function,
+                                   List<Expression> args, String targetColumn) {
+        if (!isCaseWhenSum(function, args)) {
+            return;
+        }
+        var caseWhen = (CaseWhenExpression) args.get(0);
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java:799]: Can args be empty list?

File: build.gradle [hunk 4]
```diff
@@ -191,8 +191,26 @@ dependencies {
...
 test {
-    useJUnitPlatform()
+    useJUnitPlatform {
+        excludeTags 'performance'
+    }
+    jvmArgs += '--add-opens=java.base/java.nio=ALL-UNNAMED'
+}
+
+tasks.register('perfTest', Test) {
+    description = 'Runs InfluxDB performance tests (tagged "performance"). Not part of the default test suite.'
```
Comment (KirylKurnosenka) [inline build.gradle]: taskName and tag are quite general whereas description states that it's related directly to Influx.

File: src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java (hunk 1 above)
Comment (oleksii-donets) [reply src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java:566]: Good catch. In the current code path it can't be empty — `isAggregationQuery` upstream requires ≥1 aggregation expression, and the `size == 1` branch short-circuits before any `.get(0)`. But the invariant was implicit and the failure mode (an opaque `IndexOutOfBoundsException` on line 567) would be poor if the classifier ever changed.

Fixed in 6cc820b3: moved the empty-list guard into `combineAggregations` itself so the precondition lives next to the unsafe accesses, and removed the now-redundant duplicate check in `buildWindowColumnAggregationQuery`.

File: src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java (hunk 2 above)
Comment (oleksii-donets) [reply src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java:766]: No — the only caller (line 639) gates this with `isCaseWhenSum(function, args)`, which enforces `args.size() == 1`. The precondition was implicit, though; documented it in 6cc820b3 with a javadoc note pointing to `isCaseWhenSum`.

File: src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java (hunk 3 above)
Comment (oleksii-donets) [reply src/main/java/com/epam/aidial/metric/service/influx/FluxQueryBuilder.java:799]: Self-guarded — the method's first statement is `if (!isCaseWhenSum(function, args)) return;` (line 796), and `isCaseWhenSum` enforces `args.size() == 1`. So by the time line 799 runs, `args.get(0)` is safe. No code change needed here.

File: build.gradle (hunk 4 above)
Comment (oleksii-donets) [reply build.gradle]: Fair point. The task body has no Influx-specific wiring — it just runs JUnit tests filtered by the `performance` tag, so other modules (REST, auth, etc.) could plug into the same task in the future. Broadened the description in 6cc820b3 to "Runs tests tagged 'performance'..." rather than renaming the task/tag, so the wiring stays accurate to what it actually does.

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by KirylKurnosenka — APPROVED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None
