### PR TITLE
fix: adjust model `source` field value resolution when importing core model

### LINKED ISSUE #618: [JSON Editor/Core Format] Unintended Adapter change after editing via JSON Editor in Core Format.
### Name and Version

[FE]0.13.0-rc [BE]0.13.0-rc Core:[Default version]latest

### What steps will reproduce the bug?

1. Navigate to **Entities → Models** and select a model with **Source Type: Adapter**.  
2. Enable the **JSON Editor** toggle.  
3. Switch the JSON Editor to **Core format**.  
4. Make changes to any field, for example:  
   - Update the `description` field with a new value.  
5. Save the changes.  
6. Return to the standard view and inspect the model configuration.  
7. Observe that the Adapter has been unexpectedly changed.

### What is the expected behavior?

- Saving changes in **Core format** should only modify fields that were explicitly edited, leaving other configuration fields like **Adapter** unchanged.  
- The original Adapter should remain intact, ensuring the model’s configuration consistency.

### What do you see instead?

- After saving changes made in **Core format**, the **Adapter** associated with the model is changed unintentionally.  
- The unintended change disrupts the correct configuration of the model.

Image

Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #618 

### Description of changes
Adjusted model `source` field value resolution when importing existing core model. Now during import of core model instead of setting source as existing (which could differ from current, if there are several adapters with the same base endpoint) or newly created adapter, source can be left as is in the following cases:
1. Endpoint is null in imported core model
2. Endpoint in imported core model is equal to endpoint in exisiting model
3. Endpoint in imported core model is equal to combination of exisiting model adapter base endpoint and completion endpoint path

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/test/java/com/epam/aidial/cfg/functional/tests/ModelFunctionalTest.java [hunk 1]
```diff
@@ -431,6 +432,38 @@ public void shouldSuccessfullyGetCoreModel() {
...
+        modelFacade.createModel(modelDto);
+
+        CoreModel coreModel = modelFacade.getCoreModelWithHash(modelDto.getName()).core();
+        coreModel.setDescription("New description");
+        modelFacade.updateModel(modelDto.getName(), coreModel, "*");
+
+        ModelDto expected = createModelDto("1");
+        expected.setSource(new AdapterSourceDto("adapter2", "chat/completions"));
+        expected.setDescription("New description");
+        expected.setDefaults(Map.of());
```
Comment (siarhei-fedziukovich) [inline src/test/java/com/epam/aidial/cfg/functional/tests/ModelFunctionalTest.java]: i'd remove default init and assertEquals only id+adapter. in that case test won't be affected by adding new properties with defaults

File: src/test/java/com/epam/aidial/cfg/service/config/transfer/importer/util/ModelSourceResolverTest.java [hunk 2]
```diff
@@ -0,0 +1,159 @@
...
+                .thenReturn(modelEndpointComponents);
+        when(adapterService.getByEndpoint("https://adapter"))
+                .thenReturn(adapter);
+
+        AdapterSource expected = new AdapterSource();
+        expected.setAdapterName("test-adapter");
+        expected.setCompletionEndpointPath("/completions");
+
+        // when
+        ModelSource actual = resolver.resolveSourceForExistingModel(coreModel, model);
```
Comment (siarhei-fedziukovich) [inline src/test/java/com/epam/aidial/cfg/service/config/transfer/importer/util/ModelSourceResolverTest.java]: `resolveSourceForNewModel_` in testMethod name. and resolver.`resolveSourceForExistingModel`(coreModel, model); in this line

**Review by siarhei-fedziukovich — DISMISSED** [review]

File: src/test/java/com/epam/aidial/cfg/functional/tests/ModelFunctionalTest.java (hunk 1 above)
Comment (KirylKurnosenka) [reply src/test/java/com/epam/aidial/cfg/functional/tests/ModelFunctionalTest.java]: adjusted

File: src/test/java/com/epam/aidial/cfg/service/config/transfer/importer/util/ModelSourceResolverTest.java (hunk 2 above)
Comment (KirylKurnosenka) [reply src/test/java/com/epam/aidial/cfg/service/config/transfer/importer/util/ModelSourceResolverTest.java]: nice catch, fixed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by siarhei-fedziukovich — APPROVED** [review]
