### PR TITLE
fix: Missing validation for invalid ZIP import

### LINKED ISSUE #880: [Assets][Applications/Toolsets/Files/Prompts] Missing validation for invalid ZIP import
### EPAM AI DIAL Admin version

[FE]0.16.0-rc [BE]0.16.0-rc

### How to reproduce

**Preconditions:** ZIP file that is **not a valid DIAL Admin** export is available

Affected: Asset -> **Applications**; Asset -> **Toolsets**; Asset -> **Files**;  Asset ->**Prompts**

**Steps to Reproduce**:
1. Go to **Assets** → **Applications** or/ and **Toolsets** or/ and  **Files** or/ and **Prompts**
2. Proceed with Import (file or prompts) 
3. Upload a random ZIP file (zip file not exported from Admin)
4. Proceed with Import

### Actual result

Import fails with error messages with status 200: 

for files: 

Image

for prompts: 

Image

for applications:

Image

for toolsets:

Image

### Expected result

Invalid ZIP files are validated before import starts.  The user sees a clear error message (e.g., “_Invalid archive format. Please upload a aidial-admin.zip file_”)

### Additional information

_No response_

### Confidential information

- [x] I confirm that do not share any confidential information

### PR DESCRIPTION
**Pull request by Katerina-Charakhovich**
### Applicable issues

- fixes #880 

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/service/prompt/ZipPromptEximService.java [hunk 1]
```diff
@@ -44,6 +44,8 @@ public class ZipPromptEximService {
     private static final String PROMPTS_FILENAME = "prompts.json";
     private static final String JSON_FILE_EXTENSION = ".json";
     private static final String PROMPTS_FULL_PATH = PROMPTS_FOLDER + PROMPTS_FILENAME;
+    private static final String INVALID_EXPORT_ZIP =
+            "Invalid archive format. Please upload a valid aidial-admin export ZIP.";
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/service/prompt/ZipPromptEximService.java]: I'd suggest to not highlight that archive should be exported ZIP. Theoretically I can create ZIP on my own without export

File: src/main/java/com/epam/aidial/cfg/service/FileService.java [hunk 2]
```diff
@@ -54,6 +54,9 @@
 @Slf4j
 public class FileService implements ResourceService {
 
+    private static final String INVALID_EXPORT_ZIP =
+            "Invalid archive format. Please upload a valid aidial-admin export ZIP.";
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/service/FileService.java]: I'd suggest to not highlight that archive should be exported ZIP. Theoretically I can create ZIP on my own without export

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by KirylKurnosenka — APPROVED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None
