### PR TITLE
fix: filtering of application type schema properties

### LINKED ISSUE #204: [Application Runners] Export to Core Config fails with invalid schema
### EPAM AI DIAL Admin version

0.7.0

### What happened?

Description:
Export to core config breaks if application runner type has wrong parameters.

Steps to Reproduce:

Go to Application Runners.

Create application runner with schema like:

{
  "$id": "http://DK",
  "dial:applicationTypeDisplayName": "DK-app-runner",
  "dial:applicationTypeRoutes": [
    {
      "paths": ["https://tst-tst"],
      "upstreams": [
        {
          "endpoint": "https://test-test",
          "key": "123"
        }
      ]
    }
  ]
}

Save it.

Expected:
Export works without errors.

Actual:
Export fails. Logs:

Image

### Confidential information

- [x] I confirm that do not share any confidential information

### PR DESCRIPTION
**Pull request by Pasichniuk**
### Applicable issues

- fixes #204 

### Description of changes

Application type schemas' fields filtering by schema wasn't working because in Config application type schemas are stored as JSON string instead of objects (like all other entities). Added unwrapping/wrapping logic to fix filtering & conform with other entities.

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by KirylKurnosenka — APPROVED** [review]

File: src/main/java/com/epam/aidial/cfg/service/transfer/VersionAwareFieldFilter.java [hunk 1]
```diff
@@ -180,8 +184,23 @@ private String camelToSnakeCase(String camel) {
...
-                             JsonNode parentSchema, ObjectNode filteredNode) {
+    private void processField(String fieldName, JsonNode fieldValue, JsonNode fieldSchema,
+                              JsonNode parentSchema, ObjectNode filteredNode) {
+
+        // Value of application type schema is stored as JSON string instead of object,
+        // so it needs to be unwrapped from array and wrapped to map - to conform with other entities
+        String appTypeSchemaId = null;
+        if (APPLICATION_TYPE_SCHEMAS_KEY.equals(fieldName)) {
+            JsonNode unwrappedFieldValue = unwrapAppTypeSchemaNode(fieldValue);
+            if (unwrappedFieldValue == null || unwrappedFieldValue.get("$id") == null) {
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/service/transfer/VersionAwareFieldFilter.java:195]: `unwrappedFieldValue.get("$id") == null` - what does it mean? object without id passed as valid?

Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/service/transfer/VersionAwareFieldFilter.java:195]: It means it is skipped

**Comment by siarhei-fedziukovich** [comment]
pls add tests for appTypeSchema validation

File: src/main/java/com/epam/aidial/cfg/service/transfer/VersionAwareFieldFilter.java (hunk 1 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/service/transfer/VersionAwareFieldFilter.java:195]: log it pls.

**Review by siarhei-fedziukovich — APPROVED** [review]

**Comment by Pasichniuk** [comment]
Test coverage for app type schema filtration will be improved in a separate MR
