### PR TITLE
fix: handle new ADD_IF_ABSENT publication resource action

### LINKED ISSUE #21: [File Publications] Cannot interact with publication request when file is published from conversation
### Name and Version

FE: 0.4.0-rc BE: 0.4.0-rc

### What steps will reproduce the bug?

Go to any conversation that is linked to a model.

Attach a file to the conversation.

Click the "Publish" button.

In the publish popup:

Select only "File"

Click Publish

Make sure the publication request appears in the chat (but do not approve it there).

Open the Admin panel and go to the File Publications tab.

Locate the publication request from your user.

Click on the request — nothing happens.

### What is the expected behavior?

Clicking on the request in the admin panel should open a modal or detail view to allow approve/reject actions.

### What do you see instead?

The request is visible but not interactive — no modal opens, and no action can be taken.

As a result, the file remains in a pending state indefinitely.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #21 

### Description of changes

Added handling of new ADD_IF_ABSENT publication resource action

### Checklist

- [ ] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/service/publication/resolver/url/PublicationResourceUrlResolver.java [hunk 1]
```diff
@@ -11,7 +11,7 @@ public class PublicationResourceUrlResolver {
 
     public String resolveUrl(PublicationResourceDto publicationResource, PublicationStatusDto status) {
         return switch (publicationResource.getAction()) {
-            case ADD -> resolveUrlForPublishing(publicationResource, status);
+            case ADD, ADD_IF_ABSENT -> resolveUrlForPublishing(publicationResource, status);
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/service/publication/resolver/url/PublicationResourceUrlResolver.java:14]: Accoring to the following explanation from Core team: 

> ADD_IF_ABSENT - the action gives a hint to the Core if the resource is not published then publish it otherwise skip it.

there was made a decision to resolve url the same way as for ADD action
CC: @siarhei-fedziukovich

**Review by siarhei-fedziukovich — APPROVED** [review]
