### PR TITLE
fix: add conversion. ShareResource.invitationTtl in core uses hours as time unit.

### LINKED ISSUE #355: add missing conversion for core ShareResource.invitationTtl (core uses hours as time unit.)
### Name and Version

0.9.3

### What steps will reproduce the bug?

1. create role with ShareResource.invitationTtl 

### What is the expected behavior?

HOURS is TimeUnit for core format 
MS is TimeUnit for admin format

### What do you see instead?

MS is TimeUnit for core format 
MS is TimeUnit for admin format

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by siarhei-fedziukovich**
### Applicable issues

- fixes #355

### Description of changes

add missing conversion for core ShareResource.invitationTtl (core uses hours as time unit.)

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/test/java/com/epam/aidial/cfg/functional/tests/ConfigTransferFunctionalTest.java [hunk 1]
```diff
@@ -235,7 +235,7 @@ void testImport_WithoutConflict() throws IOException {
 
         Assertions.assertThat(roleFacade.getRole("testRole1").getShare()).hasSize(1).satisfies(share -> {
             ShareResourceLimitDto shareResourceLimit = share.get(ResourceTypeDto.APPLICATION);
-            Assertions.assertThat(shareResourceLimit.getInvitationTtl()).isEqualTo(120);
+            Assertions.assertThat(shareResourceLimit.getInvitationTtl()).isEqualTo(120*(60*60*1000));
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/functional/tests/ConfigTransferFunctionalTest.java]: Can't we use already calculated value?

File: src/main/java/com/epam/aidial/cfg/domain/mapper/TimeMapper.java [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+    public Double msToHours(Long milliseconds) {
+        if (milliseconds == null) {
+            return null;
+        }
+        return ((double) milliseconds) / MS_IN_HOUR;
+    }
+
+    @Named("msToHoursWithTruncation")
+    public Long msToHoursWithTruncation(Long milliseconds) {
+        Double hours = msToHours(milliseconds);
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/domain/mapper/TimeMapper.java:23]: Doesn't it make sense to have null check before calling `msToHours` method?
E.g. if someone will mark `milliseconds` in `msToHours` as `NotNull` and remove null check, NPE could be thrown in case current method is called with `null`

File: src/test/java/com/epam/aidial/cfg/domain/mapper/TimeMapperTest.java [hunk 3]
```diff
@@ -0,0 +1,245 @@
...
+
+        // when
+        Double result = mapper.msToHours(milliseconds);
+
+        // then
+        Assertions.assertThat(result).isEqualTo(1.0);
+    }
+
+    @Test
+    void testMsToHours_NullInput() {
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/domain/mapper/TimeMapperTest.java]: Does it worth to have separate test methods instead of using parameterized test?

File: src/test/java/com/epam/aidial/cfg/domain/mapper/TimeMapperTest.java [hunk 4]
```diff
@@ -0,0 +1,245 @@
...
+        Double regularHours = mapper.msToHours(milliseconds);
+        Long truncatedHours = mapper.msToHoursWithTruncation(milliseconds);
+
+        // then
+        Assertions.assertThat(regularHours).isEqualTo(1.5);
+        Assertions.assertThat(truncatedHours).isEqualTo(1L);
+    }
+
+    @Test
+    void testConstantConsistency() {
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/domain/mapper/TimeMapperTest.java]: How this test differs from `testMsToHours_ValidInput`?

File: src/test/java/com/epam/aidial/cfg/domain/mapper/TimeMapperTest.java [hunk 5]
```diff
@@ -0,0 +1,245 @@
...
+    void testTruncationBehavior_CompareWithRegularConversion() {
+        // given
+        Long milliseconds = 5400000L; // 1.5 hours
+
+        // when
+        Double regularHours = mapper.msToHours(milliseconds);
+        Long truncatedHours = mapper.msToHoursWithTruncation(milliseconds);
+
+        // then
+        Assertions.assertThat(regularHours).isEqualTo(1.5);
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/domain/mapper/TimeMapperTest.java]: As far as I see such assertions already checked within other test methods. Not sure why this test is needed

File: src/main/java/com/epam/aidial/cfg/domain/mapper/TimeMapper.java (hunk 2 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/domain/mapper/TimeMapper.java:23]: imho this method doing casting/truncation. initial null conversion is part of msToHours logic. e.g. we can decide to convert null to 0 for all msToHours operation, in that case we have to do single change in msToHours instead of changing null conversion in different places

File: src/test/java/com/epam/aidial/cfg/functional/tests/ConfigTransferFunctionalTest.java (hunk 1 above)
Comment (siarhei-fedziukovich) [reply src/test/java/com/epam/aidial/cfg/functional/tests/ConfigTransferFunctionalTest.java]: matter of taste. it's more readable to me (compare with etalon == 120h). but we can change it to const too. will fix

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/test/java/com/epam/aidial/cfg/domain/mapper/TimeMapperTest.java (hunk 5 above)
Comment (siarhei-fedziukovich) [reply src/test/java/com/epam/aidial/cfg/domain/mapper/TimeMapperTest.java]: it's complex one. with regular conversion and conversion with truncation

File: src/test/java/com/epam/aidial/cfg/domain/mapper/TimeMapperTest.java (hunk 4 above)
Comment (siarhei-fedziukovich) [reply src/test/java/com/epam/aidial/cfg/domain/mapper/TimeMapperTest.java]: removed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/test/java/com/epam/aidial/cfg/domain/mapper/TimeMapperTest.java (hunk 3 above)
Comment (siarhei-fedziukovich) [reply src/test/java/com/epam/aidial/cfg/domain/mapper/TimeMapperTest.java]: fixed

File: src/test/java/com/epam/aidial/cfg/functional/tests/ConfigTransferFunctionalTest.java (hunk 1 above)
Comment (siarhei-fedziukovich) [reply src/test/java/com/epam/aidial/cfg/functional/tests/ConfigTransferFunctionalTest.java]: fixed

File: src/test/java/com/epam/aidial/cfg/domain/mapper/TimeMapperTest.java (hunk 5 above)
Comment (KirylKurnosenka) [reply src/test/java/com/epam/aidial/cfg/domain/mapper/TimeMapperTest.java]: `msToHours` and `msToHoursWithTruncation` are independent and we already have tests for them.
Not sure why do we need to combine them into single test

Comment (siarhei-fedziukovich) [reply src/test/java/com/epam/aidial/cfg/domain/mapper/TimeMapperTest.java]: removed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by KirylKurnosenka — DISMISSED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by KirylKurnosenka — APPROVED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>
