### PR TITLE
fix: fix import preview for non-existing adapters, add "createAdapterIfAbsent" request param to import preview endpoint to align with import endpoint

### LINKED ISSUE #70: [Import Config] Inconsistent behavior during config import - adapter initially not found, but still created
### Name and Version

0.5.0

### What steps will reproduce the bug?

1. Go to Import Config
2. Upload a few aidial.config.json 
3. Click Next - a Bad request error appears
4. Click Import - success message is shown
5. Return to Files, with the same uploaded files
6. Click Next again - this time, no error, preview is shown

### What is the expected behavior?

The system should either block import of files with invalid adapters or create the adapter immediately without error message.

### What do you see instead?

The system throws an error but creates the adapter, anyway, causing confusion.

Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #70 

### Description of changes

- Fixed import preview for non-existing adapters
- Added `createAdapterIfAbsent` request param to import preview endpoint to align with import endpoint

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/service/transfer/importer/ModelImporter.java [hunk 1]
```diff
@@ -132,4 +138,30 @@ private ModelEndpointComponents getModelEndpointComponents(CoreModel coreModel)
...
+            return null;
+        }
+
+        String adapterEndpoint = modelEndpointComponents.adapterEndpoint();
+
+        if (!isPreview) {
+            return adapterService.getByEndpoint(adapterEndpoint);
+        }
+
+        Map<String, Adapter> adaptersToCreateByBaseEndpoint = adaptersForPreview.stream()
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/service/transfer/importer/ModelImporter.java]: do you really need this map? linear search will be more efficient for this case

Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/service/transfer/importer/ModelImporter.java]: make sense, refactored

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by siarhei-fedziukovich — APPROVED** [review]
