### PR TITLE
fix: distinguish `null` and `MAX` values for role limits and role share resource limits

### LINKED ISSUE #218: [Backend] Set no limits is reset when "Make available to specific roles" toggle is turned off and a user saved "Set no limits" changes
### Name and Version

0.7.0

### What steps will reproduce the bug?

1. Open some model
2. Add Default limits and save it
3. Open Context menu of some roles
4. Click Set no limits and Save it

### What is the expected behavior?

Set no limits isn't reset when "Make available to specific roles" toggle is turned off and a user saved "Set no limits" changes

### What do you see instead?

Set no limits is reset when "Make available to specific roles" toggle is turned off and a user saved "Set no limits" changes

Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #218 

### Description of changes
Distinguish `null` and `MAX` values for role limits and role share resource limits during

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/domain/mapper/RoleLimitMapper.java [hunk 1]
```diff
@@ -40,54 +39,33 @@ default Map<String, CoreLimit> mapLimits(List<RoleLimit> roleLimits, @Context Co
...
                     CoreLimit mappedLimit = mapLimit(roleLimit.getLimit(), deployment);
-                    return mappedLimit != null ? new AbstractMap.SimpleEntry<>(roleLimit.getDeploymentName(), mappedLimit) : null;
+                    return new AbstractMap.SimpleEntry<>(roleLimit.getDeploymentName(), mappedLimit);
                 })
-                .filter(Objects::nonNull)
                 .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
     }
 
     private CoreLimit mapLimit(Limit limit, Deployment deployment) {
         if (limit == null || deployment == null) {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/domain/mapper/RoleLimitMapper.java:52]: I suppose we have incorrect state if role limit doesn't have limit (even empty) or role limit doesn't have associated deployment, so I propose to highlight that by throwing exception

File: src/main/java/com/epam/aidial/cfg/domain/mapper/RoleLimitMapper.java [hunk 2]
```diff
@@ -40,54 +39,33 @@ default Map<String, CoreLimit> mapLimits(List<RoleLimit> roleLimits, @Context Co
...
-            return null;
+            log.warn("Limit or deployment is null. Limit: {}, deployment: {}", limit, deployment);
+            throw new IllegalStateException("Limit or deployment is null");
         }
 
-        Limit defaultLimit = Optional.ofNullable(deployment.getDefaultRoleLimit()).orElse(new Limit());
-        if (isUnlimited(limit) && defaultLimit.isEmpty()) {
-            return null;
+        Limit defaultLimit = deployment.getDefaultRoleLimit();
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/domain/mapper/RoleLimitMapper.java:57]: Almost the same as previous check: deployment must always have at least empty default limit

File: src/main/java/com/epam/aidial/cfg/domain/mapper/RoleShareResourceLimitMapper.java [hunk 3]
```diff
@@ -12,19 +13,25 @@
...
-public interface RoleShareResourceLimitMapper {
+@Slf4j
+public abstract class RoleShareResourceLimitMapper extends LimitMapper {
 
-    ShareResourceLimit toLimit(CoreShareResourceLimit limit);
+    public abstract ShareResourceLimit toLimit(CoreShareResourceLimit limit);
 
-    default Map<String, CoreShareResourceLimit> mapShareResourceLimits(List<RoleShareResourceLimit> roleShareResourceLimits,
-                                                                       @Context Collection<Deployment> deployments) {
+    Long getLimit(long value) {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/domain/mapper/RoleShareResourceLimitMapper.java:28]: Added as analogue of mapping core limit default values

File: src/main/java/com/epam/aidial/cfg/domain/mapper/RoleShareResourceLimitMapper.java [hunk 4]
```diff
@@ -36,56 +43,29 @@ default Map<String, CoreShareResourceLimit> mapShareResourceLimits(List<RoleShar
...
+                    return new AbstractMap.SimpleEntry<>(roleShareResourceLimit.getDeploymentName(), mappedLimit);
                 })
-                .filter(Objects::nonNull)
                 .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
     }
 
     private CoreShareResourceLimit mapShareResourceLimit(ShareResourceLimit shareResourceLimit, Deployment deployment) {
         if (shareResourceLimit == null || deployment == null) {
-            return null;
+            log.warn("Share resource limit or deployment is null. ShareResourceLimit: {}, deployment: {}", shareResourceLimit, deployment);
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/domain/mapper/RoleShareResourceLimitMapper.java:57]: Similar check and the same explanation as in role limit mapper

File: src/main/java/com/epam/aidial/cfg/domain/mapper/RoleShareResourceLimitMapper.java [hunk 5]
```diff
@@ -36,56 +43,29 @@ default Map<String, CoreShareResourceLimit> mapShareResourceLimits(List<RoleShar
...
+            throw new IllegalStateException("Share resource limit or deployment is null");
         }
 
-        ShareResourceLimit defaultLimit = Optional.ofNullable(deployment.getDefaultRoleShareResourceLimit()).orElse(new ShareResourceLimit());
-        if (isUnlimited(shareResourceLimit) && defaultLimit.isEmpty()) {
-            return null;
+        ShareResourceLimit defaultLimit = deployment.getDefaultRoleShareResourceLimit();
+        if (defaultLimit == null) {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/domain/mapper/RoleShareResourceLimitMapper.java:62]: Similar check and the same explanation as in role limit mapper

File: src/main/java/com/epam/aidial/cfg/domain/mapper/LimitMapper.java [hunk 6]
```diff
@@ -0,0 +1,18 @@
...
+
+public abstract class LimitMapper {
+
+    protected <T> void setIfNotNull(Consumer<T> setter, T value) {
+        if (value != null) {
+            setter.accept(value);
+        }
+    }
+
+    protected <T, R> T getLimitOrDefault(R limit, R defaultLimit, Function<R, T> limitValueGetter) {
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/domain/mapper/LimitMapper.java]: i'd move both method in commons.utils. there are no limits specific in both. they are completely generic
and would rename getLimitOrDefault -> getValueOrDefault

File: src/main/java/com/epam/aidial/cfg/domain/mapper/RoleLimitMapper.java (hunk 1 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/domain/mapper/RoleLimitMapper.java:52]: do we need migration here?

File: src/main/java/com/epam/aidial/cfg/domain/mapper/RoleLimitMapper.java (hunk 2 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/domain/mapper/RoleLimitMapper.java:57]: do we need migration here as well?

Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/domain/mapper/RoleLimitMapper.java:57]: Didn't get why

File: src/main/java/com/epam/aidial/cfg/domain/mapper/RoleShareResourceLimitMapper.java (hunk 4 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/domain/mapper/RoleShareResourceLimitMapper.java:57]: migration for share limits too here and below

File: src/main/java/com/epam/aidial/cfg/domain/mapper/RoleLimitMapper.java (hunk 2 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/domain/mapper/RoleLimitMapper.java:57]: For the reference https://github.com/epam/ai-dial-admin-backend/blob/3a5903bcafd8205b8afeaf9ea8cf8d1e0c6be399/src/main/java/com/epam/aidial/cfg/dao/mapper/DeploymentEntityMapper.java#L93

File: src/test/resources/mapper/core/role_limit/map_limits/core_limits.json [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+  "deployment3": {
+    "minute": 9223372036854775807,
+    "day": 9223372036854775807,
+    "week": 9223372036854775807,
+    "month": 9223372036854775807,
+    "requestHour": 9223372036854775807,
+    "requestDay": 9223372036854775807
+  },
+  "deployment4": {
+    "minute": 9223372036854775807,
```
Comment (siarhei-fedziukovich) [inline src/test/resources/mapper/core/role_limit/map_limits/core_limits.json:27]: i'd left one limit empty (e.g. "deployment4": {}) to test default value mapping. and it's main limits declaration in real worlds core configs.

File: src/test/resources/mapper/core/role_limit/map_limits/deployments.json [hunk 8]
```diff
@@ -0,0 +1,32 @@
...
+      "day": 10
+    }
+  },
+  {
+    "name": "deployment4",
+    "defaultRoleLimit": {}
+  },
+  {
+    "name": "deployment5",
+    "defaultRoleLimit": {}
```
Comment (siarhei-fedziukovich) [inline src/test/resources/mapper/core/role_limit/map_limits/deployments.json:28]: to spread coverage. propose to add few fields with maxValue here

File: src/test/resources/mapper/core/role_share_resource_limit/map_share_resource_limits/deployments.json [hunk 9]
```diff
@@ -0,0 +1,44 @@
...
+    "defaultRoleShareResourceLimit": {
+      "maxAcceptedUsers": 10,
+      "invitationTtl": null
+    }
+  },
+  {
+    "name": "deployment3",
+    "defaultRoleShareResourceLimit": {
+      "maxAcceptedUsers": 10,
+      "invitationTtl": null
```
Comment (siarhei-fedziukovich) [inline src/test/resources/mapper/core/role_share_resource_limit/map_share_resource_limits/deployments.json:19]: remove invitationTtl field for some of the default resource limits. to test withdefault value

File: src/test/resources/mapper/core/role_limit/map_limits/core_limits.json [hunk 10]
```diff
@@ -0,0 +1,50 @@
+{
+  "deployment1": {
+    "minute": 9223372036854775807,
```
Comment (siarhei-fedziukovich) [inline src/test/resources/mapper/core/role_limit/map_limits/core_limits.json:3]: does we creates such json for core? with all this maxValues? can we left it empty in core if it's maxValue. it's increase readability and reduce size of config json

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/test/resources/mapper/core/role_limit/map_limits/core_limits.json (hunk 10 above)
Comment (KirylKurnosenka) [reply src/test/resources/mapper/core/role_limit/map_limits/core_limits.json:3]: adjusted

File: src/test/resources/mapper/core/role_limit/map_limits/deployments.json (hunk 8 above)
Comment (KirylKurnosenka) [reply src/test/resources/mapper/core/role_limit/map_limits/deployments.json:28]: Added for deployment1

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/test/resources/mapper/core/role_share_resource_limit/map_share_resource_limits/deployments.json (hunk 9 above)
Comment (KirylKurnosenka) [reply src/test/resources/mapper/core/role_share_resource_limit/map_share_resource_limits/deployments.json:19]: removed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/domain/mapper/RoleLimitMapper.java [hunk 11]
```diff
@@ -40,54 +42,47 @@ default Map<String, CoreLimit> mapLimits(List<RoleLimit> roleLimits, @Context Co
...
-                .filter(Objects::nonNull)
+                .filter(entry -> isLimited(entry.getValue()))
                 .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
     }
 
     private CoreLimit mapLimit(Limit limit, Deployment deployment) {
         if (limit == null || deployment == null) {
-            return null;
+            log.warn("Limit or deployment is null. Limit: {}, deployment: {}", limit, deployment);
+            throw new IllegalStateException("Limit or deployment is null");
```
Comment (Pasichniuk) [inline src/main/java/com/epam/aidial/cfg/domain/mapper/RoleLimitMapper.java:54]: IllegalArgumentException is more suitable here (and other places in this PR) since we validate incoming parameters, not the state of object

Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/domain/mapper/RoleLimitMapper.java:54]: Make sense, but IllegalArgumentException maps to 400 Bad request, while in this case it's not a client error but invalid state of application itself

File: src/main/java/com/epam/aidial/cfg/domain/mapper/LimitMapper.java (hunk 6 above)
Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/domain/mapper/LimitMapper.java]: Moved into NullSafeUtils

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by siarhei-fedziukovich — APPROVED** [review]

File: src/test/resources/mapper/core/role_limit/map_limits/core_limits.json (hunk 10 above)
Comment (siarhei-fedziukovich) [reply src/test/resources/mapper/core/role_limit/map_limits/core_limits.json:3]: will be fixes in separate techdebt task

Comment (KirylKurnosenka) [reply src/test/resources/mapper/core/role_limit/map_limits/core_limits.json:3]: Tech debt https://github.com/epam/ai-dial-admin-backend/issues/230
