### PR TITLE
fix: set `parallelToolCallsSupported` to true if missing during core config import + minor refactoring

### LINKED ISSUE #219: [Import] Default values in Features not applied after model import
### EPAM AI DIAL Admin version

0.7.0-rc

### What happened?

When importing a model, some parameters in the Features section are not set by default, even though they should be.
For example, the parallel tool calls parameter remains empty after the initial import.
However, if you make any changes to the model (e.g., set an adapter in the Properties tab and save), then check the Audit, you will see that parallel tool calls was empty at first, but after the change it becomes true.

Steps to Reproduce:
Import a model.
Modify the model (e.g., set an adapter in Properties) and save.
Go to the Audit tab and check changes.

Actual Behavior:
Parameter "parallel tool calls" is not set by default after import.
It's only set after making and saving a change.

Expected Behavior:
Default values for parameters in Features (such as parallel tool calls) should be applied immediately upon model import, without requiring further edits.

### Confidential information

- [x] I confirm that do not share any confidential information

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #219 

### Description of changes
1) set `parallelToolCallsSupported` to true if missing during core config import
2) refactored mappers

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/domain/model/Features.java [hunk 1]
```diff
@@ -40,5 +40,5 @@ public class Features {
     private Boolean cacheSupported;
     private Boolean autoCachingSupported;
     private Boolean consentRequired;
-    private Boolean parallelToolCallsSupported = true;
+    private boolean parallelToolCallsSupported = true;
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/domain/model/Features.java:43]: This is the main change: 
When `parallelToolCallsSupported` was missing in `CoreFeatures` during import, it has `null` value and that value was assigned to `parallelToolCallsSupported` field in `Features` ignoring its default value
With using boolean primitive `null` value in `CoreFeatures` is ignored and default `true` value is left in `Features`

**Review by siarhei-fedziukovich — APPROVED** [review]
