### PR TITLE
fix: change endpoint validation logic

### LINKED ISSUE #133: Interceptor does not accept .local or relative URLs as valid
### Name and Version

0.6.0

### What steps will reproduce the bug?

1. Go to DIAL Admin
2. Open Entities -> Interceptors
3. Open any interceptors
4. Enter http://dial-interceptor-example.dial-development/openai/deployments/image-watermark/chat/completions
in endpoint field
5.Click Save

### What is the expected behavior?

URLs  with relative path like .com, .ru /... should be accepted for testing environment

### What do you see instead?

Validation fails

Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Pasichniuk**
### Applicable issues

- fixes #133 

### Description of changes

Updated endpoint validation logic to ease strictness.

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/domain/validator/EndpointValidator.java [hunk 1]
```diff
@@ -4,18 +4,25 @@
...
         return !isValidUrl(url);
     }
 
     public static boolean isValidUrl(String url) {
+        if (!VALID_URL_PATTERN.matcher(url).matches()) {
+            return false;
+        }
         String[] schemes = {"http", "https"};
-        var validator = new UrlValidator(schemes, ALLOW_LOCAL_URLS);
+        var validator = new CustomUrlValidator(schemes, ALLOW_LOCAL_URLS);
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/domain/validator/EndpointValidator.java]: May be validator can be created once?

Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/domain/validator/EndpointValidator.java]: Yes, extracted to a static variable

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by siarhei-fedziukovich — APPROVED** [review]

**Review by KirylKurnosenka — APPROVED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None
