### PR TITLE
fix: allow internal service names in upstream endpoint [#9]

### LINKED ISSUE #9: [Routes] User cannot add short URL to the upstream
### Name and Version

ai dial admin 0.4.0

### What steps will reproduce the bug?

1. Go to the Routes page
2. Open the _test yd_ entity
3. Try to add the following URL: http://ai-dial-crol-backend:50/ to the Upstream Endpoints nut field

### What is the expected behavior?

The link is added and can be saved

### What do you see instead?

The link cannot be saved

### Additional information

Image

### PR DESCRIPTION
**Pull request by Pasichniuk**
### Applicable issues

- fixes #9 

### Description of changes

1. Made the TLD part optional
2. Added explicit support for port numbers
3. Removed the requirement for "www." prefix
4. Simplified the hostname pattern to allow internal service names

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
Hey there and thank you for opening this pull request! 👋🏼

We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

Details:

```
No release type found in pull request title "fix[#9]: allow internal service names in upstream endpoint". Add a prefix to indicate what kind of release this pull request corresponds to. For reference, see https://www.conventionalcommits.org/

Available types:
 - fix
 - hotfix
 - feat
 - feature
 - chore
```

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/dto/validation/annotation/UpstreamEndpoint.java [hunk 1]
```diff
@@ -12,7 +12,7 @@
 import static java.lang.annotation.RetentionPolicy.RUNTIME;
 
 @Constraint(validatedBy = {})
-@Pattern(regexp = "https?://(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)", message = "Invalid upstream endpoint")
+@Pattern(regexp = "https?://[-a-zA-Z0-9@:%._\\+~#=]{1,256}(\\.[a-zA-Z0-9()]{1,6})?\\b(:[0-9]{1,5})?([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)", message = "Invalid upstream endpoint")
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/dto/validation/annotation/UpstreamEndpoint.java:15]: add tests pls

Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/dto/validation/annotation/UpstreamEndpoint.java:15]: done

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Snapshot Warnings</h2>
<blockquote>⚠️: The number of snapshots compared for the base SHA (2) and the head SHA (1) do not match. You may see unexpected removals in the diff.</blockquote>
Re-running this action after a short time may resolve the issue. See <a href=https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#best-practices-for-using-the-dependency-review-api-and-the-dependency-submission-api-together>the documentation</a> for more information and troubleshooting advice.<h2>Scanned Files</h2>
None

**Review by siarhei-fedziukovich — APPROVED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Snapshot Warnings</h2>
<blockquote>⚠️: The number of snapshots compared for the base SHA (2) and the head SHA (1) do not match. You may see unexpected removals in the diff.</blockquote>
Re-running this action after a short time may resolve the issue. See <a href=https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#best-practices-for-using-the-dependency-review-api-and-the-dependency-submission-api-together>the documentation</a> for more information and troubleshooting advice.<h2>Scanned Files</h2>
None
