### PR TITLE
fix: #144 Validate datasource.vendor

### LINKED ISSUE #144: [Tech Debt] Validate `datasource.vendor` application property
### Name and Version

ai-dial-admin

### What is the problem this feature will solve?

The feature should solve the problem when invalid value is set to `datasource.vendor` property and application is started with in-memory H2 by default and missing migration scripts

### What is the feature you are proposing to solve the problem?

There should be validation for `datasource.vendor` property. Startup should be failed if value is invalid

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by siarhei-fedziukovich**
…pplicationEnvironmentPreparedEvent

### Applicable issues

- fixes #144

### Description of changes

Validate datasource.vendor before Flyway migrations

Replace @PostConstruct validation with ApplicationListener<ApplicationEnvironmentPreparedEvent>
to ensure validation runs before Flyway auto-configuration resolves migration paths.

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/Application.java [hunk 1]
```diff
@@ -11,6 +12,8 @@
 @EnableAspectJAutoProxy
 public class Application {
     public static void main(String[] args) {
-        SpringApplication.run(Application.class, args);
+        SpringApplication application = new SpringApplication(Application.class);
+        application.addListeners(new DatasourceVendorProperties());
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/Application.java]: Can't the listener be registered in declarative way, e.g. `@Component`, `@EventListener`?

Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/Application.java]: migration starts before application context is created. and we will see strange error related to migration instead of clear exception which say that datasource-vendor is incorrect

File: src/main/java/com/epam/aidial/cfg/configuration/DatasourceVendorProperties.java [hunk 2]
```diff
@@ -2,23 +2,23 @@
...
+import org.springframework.context.ApplicationListener;
+import org.springframework.core.env.Environment;
 
 import java.util.Set;
-import javax.annotation.PostConstruct;
 
 @Slf4j
-@Configuration
-public class DatasourceVendorProperties {
+public class DatasourceVendorProperties implements ApplicationListener<ApplicationEnvironmentPreparedEvent> {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/configuration/DatasourceVendorProperties.java]: DatasourceVendorProperties is confusing since it doesn't hold any app properties at all.
Maybe it make sense to rename to smth like DatasourceVendorValidator or similar?

Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/configuration/DatasourceVendorProperties.java]: renamed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by KirylKurnosenka — APPROVED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>
