### PR TITLE
fix:  Export files should include last folder from a path

### LINKED ISSUE #728: [Assets][Files] Files and subfolders are not include when exporting a folder
### Name and Version

[FE]0.15.0-rc [BE]0.15.0-rc

### What steps will reproduce the bug?

BE support is required. Related to FE bug:   https://github.com/epam/ai-dial-admin-frontend/issues/2427 

Go to Assets → Files.
Select a folder that contains:
• Files directly inside it
• One or more subfolders (with files inside them).
Click Export.
Open the exported archive.

### What is the expected behavior?

The export should include: All files inside the selected folder; All nested subfolders; All files inside subfolders.

### What do you see instead?

• Only the selected folder is exported.
• Files inside the folder are missing.
• Subfolders and their files are not included in the export.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Katerina-Charakhovich**
### Applicable issues

- fixes #728 

### Checklist

- [ ] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/service/FileService.java [hunk 1]
```diff
@@ -322,12 +322,32 @@ public boolean fileExists(String path) {
...
+        }
+        return entries;
+    }
+
+    private void addFolderExportEntries(Map<String, String> entries, String path) {
+        var folderName = PathUtils.folderNameWithoutPath(path);
+        var archiveFolderPath = "public/" + folderName;
+        for (String filePath : collectFilePathsByPath(path)) {
+            var fileName = PathUtils.parsePath(filePath).getName();
+            entries.putIfAbsent(filePath, archiveFolderPath + fileName);
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/service/FileService.java]: `ifAbsent` silently ignores collissions

File: src/main/java/com/epam/aidial/cfg/service/FileService.java [hunk 2]
```diff
@@ -322,12 +322,32 @@ public boolean fileExists(String path) {
...
     }
 
-    private Set<String> resolveExportPaths(ExportResource exportResource) {
-        Set<String> paths = new HashSet<>();
+    private Map<String, String> resolveExportFileEntries(ExportResource exportResource) {
+        Map<String, String> entries = new HashMap<>();
         for (String path : exportResource.getPaths()) {
-            paths.addAll(collectFilePathsByPath(path));
+            if (PathUtils.isFolderPath(path)) {
+                addFolderExportEntries(entries, path);
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/service/FileService.java:329]: not truly recursive?

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/service/FileService.java (hunk 2 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/service/FileService.java:329]: According to the API documentation core (https://dialx.ai/dial_api#tag/Files/operation/getFileMetadata), already returns a flat list of all files under the given path. ([link](https://github.com/epam/ai-dial-admin-backend/blob/83ee96864ac91e7191e46fbbd26ffc11cdb78559/src/main/java/com/epam/aidial/cfg/service/FileService.java#L358))
So no additional recursion is required on our side — addFolderExportEntries simply processes the flattened result.

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/service/FileService.java (hunk 1 above)
Comment (Katerina-Charakhovich) [reply src/main/java/com/epam/aidial/cfg/service/FileService.java]: updated

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.3.1</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.3.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by siarhei-fedziukovich — APPROVED** [review]
