### PR TITLE
fix: #427 add validation for displayName&endpoint in CreateToolSetResourceDto

### LINKED ISSUE #427: [Assets /Toolsets] Missing Validation in JSON Editor allows invalid data saving for Toolset fields.
### EPAM AI DIAL Admin version

FE: 0.11.0-rc BE: 0.11.0-rc

### How to reproduce

1. Navigate to **Assets/Toolsets**.  
2. Select an existing Toolset or create a new one.  
3. Open the Toolset details and switch to the **JSON Editor** view.  
4. Edit the values of the following fields directly in the JSON structure:  
   - `Display name`  
   - `External Endpoint`  
5. Save the changes made in JSON Editor mode.

### Actual result

- No validation checks are performed for changes made in JSON Editor mode.  
- Invalid values are applied and saved, despite these fields requiring validation in other editing modes. 

Image

Image

Image

Image

### Expected result

- The JSON Editor should validate fields like **Display Name** and **External Endpoint**, ensuring the input is proper and adheres to predefined format and constraints.  
- If invalid values are entered, the system should display an appropriate validation error message.  
- The system should restrict saving changes until all fields pass validation.   

### Confidential information

- [x] I confirm that do not share any confidential information

### PR DESCRIPTION
**Pull request by siarhei-fedziukovich**
### Applicable issues

- fixes #427

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/dto/validation/annotation/ValidEndpoint.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+import java.lang.annotation.Target;
+
+import static java.lang.annotation.ElementType.FIELD;
+import static java.lang.annotation.RetentionPolicy.RUNTIME;
+
+@Constraint(validatedBy = {ValidEndpointValidator.class})
+@Documented
+@Retention(RUNTIME)
+@Target(FIELD)
+public @interface ValidEndpoint {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/dto/validation/annotation/ValidEndpoint.java]: Actually such annotations do not have `Valid` prefix, so I'd suggest to use just `@Endpoint`
Also `org.hibernate.validator.constraints.URL` can be considered as an alternative

File: src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java [hunk 2]
```diff
@@ -218,6 +221,57 @@ void testCreateToolSetResource_whenResourcePresent() throws Exception {
...
+        // Test with null displayName
+        var dtoNullDisplayName = objectMapper.readValue(createToolSetDtoJson, CreateToolSetResourceDto.class);
+        dtoNullDisplayName.setDisplayName(null);
+        var jsonNullDisplayName = objectMapper.writeValueAsString(dtoNullDisplayName);
+
+        mockMvc.perform(post(CREATE_API_PATH)
+                        .contentType(MediaType.APPLICATION_JSON)
+                        .content(jsonNullDisplayName))
+                .andExpect(status().isBadRequest())
+                .andExpect(jsonPath("$.message").value(Matchers.containsString("displayName")));
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java]: Can we check full error message?

File: src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java [hunk 3]
```diff
@@ -218,6 +221,57 @@ void testCreateToolSetResource_whenResourcePresent() throws Exception {
         verify(toolSetResourceService).createToolSetResource(eq(createToolSet));
     }
 
+    @Test
+    void testCreateInvalidToolSetsResource() throws Exception {
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java]: Can we split the test per each case

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/dto/validation/annotation/ValidEndpoint.java (hunk 1 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/dto/validation/annotation/ValidEndpoint.java]: renamed

File: src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java (hunk 2 above)
Comment (siarhei-fedziukovich) [reply src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java]: done

File: src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java (hunk 3 above)
Comment (siarhei-fedziukovich) [reply src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java]: splitted

File: src/main/java/com/epam/aidial/cfg/dto/validation/validator/ValidEndpointValidator.java [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+
+import com.epam.aidial.cfg.domain.validator.EndpointValidator;
+import com.epam.aidial.cfg.dto.validation.annotation.Endpoint;
+import jakarta.validation.ConstraintValidator;
+import jakarta.validation.ConstraintValidatorContext;
+import lombok.extern.slf4j.Slf4j;
+import org.apache.commons.lang3.StringUtils;
+
+@Slf4j
+public class ValidEndpointValidator implements ConstraintValidator<Endpoint, String> {
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/dto/validation/validator/ValidEndpointValidator.java]: just `EndpointValidator` should be enough

File: src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java [hunk 5]
```diff
@@ -218,6 +220,72 @@ void testCreateToolSetResource_whenResourcePresent() throws Exception {
...
+        dtoInvalidEndpoint.setEndpoint("invalid-url");
+        var jsonInvalidEndpoint = objectMapper.writeValueAsString(dtoInvalidEndpoint);
+
+        mockMvc.perform(post(CREATE_API_PATH)
+                        .contentType(MediaType.APPLICATION_JSON)
+                        .content(jsonInvalidEndpoint))
+                .andExpect(status().isBadRequest())
+                .andExpect(jsonPath("$.message").value("endpoint: Invalid endpoint URL"));
+
+        verifyNoInteractions(toolSetResourceService);
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java:292]: Shouldn't that be added to all new tests?

File: src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java [hunk 6]
```diff
@@ -218,6 +220,72 @@ void testCreateToolSetResource_whenResourcePresent() throws Exception {
         verify(toolSetResourceService).createToolSetResource(eq(createToolSet));
     }
 
+    @Test
+    void testCreateToolSetsResourceWithUndefinedDisplayName() throws Exception {
```
Comment (KirylKurnosenka) [inline src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java]: I think singular form createToolSetResource... should be used

File: src/main/java/com/epam/aidial/cfg/dto/validation/validator/ValidEndpointValidator.java (hunk 4 above)
Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/dto/validation/validator/ValidEndpointValidator.java]: ok

File: src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java (hunk 5 above)
Comment (siarhei-fedziukovich) [reply src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java:292]: fixed

File: src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java (hunk 6 above)
Comment (siarhei-fedziukovich) [reply src/test/java/com/epam/aidial/cfg/web/controller/none/ToolSetResourceControllerTest.java]: fixed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by KirylKurnosenka — APPROVED** [review]
