### PR TITLE
fix: save and return only unique topics

### LINKED ISSUE #179: [Topics] Topics are duplicated multiple times in existing Applications, Models
### EPAM AI DIAL Admin version

0.7.0.

### How to reproduce

1. Go to any existing **Application** or **Model**.
2. Observe the displayed **Topics**.
4. Check the same Application/Model in the Marketplace view.

### Actual result

• Each Topic name appears multiple times (up to 5 or more duplicates).
• The same duplication is visible in the Marketplace.
• Duplicated Topics cannot be removed.

Image

### Expected result

• Each Topic should be displayed only once.

### Confidential information

- [x] I confirm that do not share any confidential information

### PR DESCRIPTION
**Pull request by KirylKurnosenka**
### Applicable issues

- fixes #179

### Description of changes
Used LinkedHashSet for topics in order to preserve order and uniqueness

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/cfg/domain/model/Application.java [hunk 1]
```diff
@@ -23,7 +24,7 @@ public class Application extends RoleBased {
     private List<String> inputAttachmentTypes;
     private Integer maxInputAttachments;
     private Boolean forwardAuthToken;
-    private List<String> descriptionKeywords;
+    private LinkedHashSet<String> descriptionKeywords;
```
Comment (siarhei-fedziukovich) [inline src/main/java/com/epam/aidial/cfg/domain/model/Application.java:27]: why do you use LinkedHashSet<> instead of base Set<> ?

Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/domain/model/Application.java:27]: I think it would be good to preserve order

Comment (siarhei-fedziukovich) [reply src/main/java/com/epam/aidial/cfg/domain/model/Application.java:27]: let it be

**Review by siarhei-fedziukovich — APPROVED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>3.19.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>3.19.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>
