### PR TITLE
fix: add default value for maxRetryAttempts & appendApplicationPropertiesHeader

### LINKED ISSUE #243: `maxRetryAttempts` should be 1 by default. and can not be less than 1 (validation)
### Name and Version

0.7.0

### What steps will reproduce the bug?

1. create empty model
2. get new model

### What is the expected behavior?

maxRetryAttempts should be 1

### What do you see instead?

maxRetryAttempts is undefined (== 0 by default for int)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Pasichniuk**
### Applicable issues

- fixes #243 

### Description of changes

- Added default value 'true' for 'appendApplicationPropertiesHeader' property in ApplicationTypeSchema and migrated existing data where 'appendApplicationPropertiesHeader' is NULL to have default value.
- Added default value '1' for 'maxRetryAttempts' property in Model, Application, Route and ToolSet. Migrated existing data where 'maxRetryAttempts' is NULL, equal or less than zero.
- Added validation for 'maxRetryAttempts' to be greater than zero.

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/dto/ApplicationDto.java [hunk 1]
```diff
@@ -34,6 +35,7 @@ public class ApplicationDto extends RoleBasedDto {
     private Map<String, Object> defaults;
     private List<String> interceptors;
     private List<String> topics;
+    @Min(value = 1, message = "Max retry attempts should be greater than 0")
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/dto/ApplicationDto.java]: @Positive can be used

**Review by siarhei-fedziukovich — DISMISSED** [review]

File: src/main/resources/db/migration/H2/V1.61__AddDefaultForAppPropertiesHeaderAndMaxRetryAttempts.sql [hunk 2]
```diff
@@ -0,0 +1,42 @@
+-- Update application_type_schema_entity
+UPDATE application_type_schema_entity SET append_application_properties_header = true WHERE append_application_properties_header IS NULL;
+ALTER TABLE application_type_schema_entity ALTER COLUMN append_application_properties_header SET DEFAULT true;
```
Comment (KirylKurnosenka) [inline src/main/resources/db/migration/H2/V1.61__AddDefaultForAppPropertiesHeaderAndMaxRetryAttempts.sql]: May be lets make column not null as well as max_retry_attempts

Comment (KirylKurnosenka) [reply src/main/resources/db/migration/H2/V1.61__AddDefaultForAppPropertiesHeaderAndMaxRetryAttempts.sql]: And make field type as small boolean in ApplicationTypeSchemaEntity

File: src/main/resources/db/migration/MS_SQL_SERVER/V1.61__AddDefaultForAppPropertiesHeaderAndMaxRetryAttempts.sql [hunk 3]
```diff
@@ -0,0 +1,72 @@
+-- Update application_type_schema_entity
+UPDATE application_type_schema_entity
```
Comment (KirylKurnosenka) [inline src/main/resources/db/migration/MS_SQL_SERVER/V1.61__AddDefaultForAppPropertiesHeaderAndMaxRetryAttempts.sql]: Why formatting differs from H2 or Postgres?

File: src/main/java/com/epam/aidial/cfg/dto/ApplicationDto.java (hunk 1 above)
Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/dto/ApplicationDto.java]: Changed, thanks

File: src/main/resources/db/migration/H2/V1.61__AddDefaultForAppPropertiesHeaderAndMaxRetryAttempts.sql (hunk 2 above)
Comment (Pasichniuk) [reply src/main/resources/db/migration/H2/V1.61__AddDefaultForAppPropertiesHeaderAndMaxRetryAttempts.sql]: Done

File: src/main/resources/db/migration/MS_SQL_SERVER/V1.61__AddDefaultForAppPropertiesHeaderAndMaxRetryAttempts.sql (hunk 3 above)
Comment (Pasichniuk) [reply src/main/resources/db/migration/MS_SQL_SERVER/V1.61__AddDefaultForAppPropertiesHeaderAndMaxRetryAttempts.sql]: Fixed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/cfg/dto/DeploymentDto.java [hunk 4]
```diff
@@ -45,5 +46,6 @@ public class DeploymentDto extends RoleBasedDto {
 
     private List<String> topics;
 
+    @Min(value = 1, message = "Max retry attempts should be greater than 0")
```
Comment (KirylKurnosenka) [inline src/main/java/com/epam/aidial/cfg/dto/DeploymentDto.java]: Still @Min used

Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/dto/DeploymentDto.java]: Actually this DeploymentDto is unused, maybe we should delete it?

Comment (KirylKurnosenka) [reply src/main/java/com/epam/aidial/cfg/dto/DeploymentDto.java]: yes, let's delete

Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/cfg/dto/DeploymentDto.java]: Removed

**Review by KirylKurnosenka — APPROVED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None
